### ISSUE TITLE
Light client panics on PoA chain

### ISSUE THREAD

**Issue by jhedev** [paritytech/parity-ethereum#10025]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: master
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: tobalaba
- **Restarted**: yes

I compiled the client (`cargo build --release`) on an `a1.xlarge` on AWS (it's an ARMv8 64-Bit - aarch64 processor). As soon as I start the client in light mode it fails with the stack trace attached below. 

If I run it without the `--light` flag it starts synching. 

```shell
$ target/release/parity --chain tobalaba --light
2018-12-06 13:09:35 UTC Starting Parity-Ethereum/v2.3.0-unstable-d19bdb6-20181206/aarch64-linux-gnu/rustc1.30.1
2018-12-06 13:09:35 UTC Keys path /home/ubuntu/.local/share/io.parity.ethereum/keys/Tobalaba
2018-12-06 13:09:35 UTC DB path /home/ubuntu/.local/share/io.parity.ethereum/chains_light/Tobalaba/db/5b5adf025532f2b0
2018-12-06 13:09:35 UTC Running in experimental Light Client mode.
2018-12-06 13:09:35 UTC Debug API is not available in light client mode.
2018-12-06 13:09:35 UTC Debug API is not available in light client mode.
2018-12-06 13:09:38 UTC Signal for transition within contract. New list: [0x4ba15b56452521c0826a35a6f2022e1210fc519b, 0xb5e8c1bf705f10bf4531941600f7d0a5bab7f5e8]


====================

stack backtrace:
   0:     0xaaaab3dedf73 - backtrace::backtrace::trace::h6cb2fdd1a3581ed7
   1:     0xaaaab3ded203 - <backtrace::capture::Backtrace as core::default::Default>::default::he6df877841bd711f
   2:     0xaaaab3dec683 - panic_hook::gen_panic_msg::ha286f0630f86316f
   3:     0xaaaab29ed927 - panic_hook::set_with::{{closure}}::h4f65db452a2ac92e
   4:     0xaaaab3e3d243 - std::panicking::rust_panic_with_hook::h7d39a7695d8da98f
                        at libstd/panicking.rs:481
   5:     0xaaaab3e3ce4f - std::panicking::continue_panic_fmt::ha287897123d4a956
                        at libstd/panicking.rs:391
   6:     0xaaaab3e3cd5b - rust_begin_unwind
                        at libstd/panicking.rs:326
   7:     0xaaaab3e648a3 - core::panicking::panic_fmt::h2155aa66b67fe83c
                        at libcore/panicking.rs:77
   8:     0xaaaab3e648f3 - core::option::expect_failed::h0ee1e896fd083f84
                        at libcore/option.rs:1000
   9:     0xaaaab34a43ef - <ethcore::engines::authority_round::AuthorityRound as ethcore::engines::Engine<ethcore::machine::EthereumMachine>>::is_epoch_end::h3d4ae2367aec17aa
  10:     0xaaaab34a3cd7 - <ethcore::engines::authority_round::AuthorityRound as ethcore::engines::Engine<ethcore::machine::EthereumMachine>>::is_epoch_end_light::hd8b447c81a5e8193
  11:     0xaaaab2c2754b - <ethcore_light::client::Client<T>>::import_verified::he87f01129e9f3b47
  12:     0xaaaab35c351b - <ethcore_io::service_mio::IoChannel<Message>>::send_sync::h470bf070f3a6068d
  13:     0xaaaab3536e2b - ethcore::verification::queue::QueueSignal::set_sync::hfb99d7f710d0c040
  14:     0xaaaab2e6927b - <ethcore::verification::queue::VerificationQueue<K>>::verify::h1ab5378e27c0360b
  15:     0xaaaab2e4a153 - std::panicking::try::do_call::h8ccd97353148efd8
  16:     0xaaaab3e6079f - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:103
  17:     0xaaaab2c41367 - <F as alloc::boxed::FnBox<A>>::call_box::h3dbb18d0f0a8e910
  18:     0xaaaab3e556ef - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h85424732c346e3af
                        at liballoc/boxed.rs:656
                         - std::sys_common::thread::start_thread::h41cf1ad8630babd4
                        at libstd/sys_common/thread.rs:24
  19:     0xaaaab3e43f9b - std::sys::unix::thread::Thread::new::thread_start::hbd34cf20156b5b37
                        at libstd/sys/unix/thread.rs:90
  20:     0xffffbb05bfc3 - start_thread

Thread 'Verifier #2' panicked at 'header is finalized; finalized headers must exist in the chain; qed', libcore/option.rs:1000

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new



====================

stack backtrace:
   0:     0xaaaab3dedf73 - backtrace::backtrace::trace::h6cb2fdd1a3581ed7
   1:     0xaaaab3ded203 - <backtrace::capture::Backtrace as core::default::Default>::default::he6df877841bd711f
   2:     0xaaaab3dec683 - panic_hook::gen_panic_msg::ha286f0630f86316f
   3:     0xaaaab29ed927 - panic_hook::set_with::{{closure}}::h4f65db452a2ac92e
   4:     0xaaaab3e3d243 - std::panicking::rust_panic_with_hook::h7d39a7695d8da98f
                        at libstd/panicking.rs:481
   5:     0xaaaab3e3ce4f - std::panicking::continue_panic_fmt::ha287897123d4a956
                        at libstd/panicking.rs:391
   6:     0xaaaab3e3cd5b - rust_begin_unwind
                        at libstd/panicking.rs:326
   7:     0xaaaab3e648a3 - core::panicking::panic_fmt::h2155aa66b67fe83c
                        at libcore/panicking.rs:77
   8:     0xaaaab2cdd457 - core::result::unwrap_failed::hea3f4b9b02297044
   9:     0xaaaab2e74c5f - <ethcore::verification::queue::VerificationQueue<K> as core::ops::drop::Drop>::drop::h3a27cfb8799827ae
  10:     0xaaaab2e55773 - core::ptr::drop_in_place::h8c0c338ecf314071
  11:     0xaaaab2e5b56b - core::ptr::drop_in_place::hde35f2f32ed620ee
  12:     0xaaaab2e3ff8f - <alloc::sync::Arc<T>>::drop_slow::h28ea1a9759c73a5a
  13:     0xaaaab2e46e3b - <alloc::sync::Arc<T>>::drop_slow::hc25d2317d16f84f5
  14:     0xaaaab2cd4df7 - core::ptr::drop_in_place::h6c7f0ba220b24d22
  15:     0xaaaab32453b7 - <alloc::sync::Arc<T>>::drop_slow::h1e888ce8eb309d4d
  16:     0xaaaab322c2e3 - core::ptr::drop_in_place::h10269e70b975ee33
  17:     0xaaaab2e3df67 - <alloc::sync::Arc<T>>::drop_slow::h079db1eaa8e3b0db
  18:     0xaaaab301ebaf - <std::collections::hash::table::RawTable<K, V> as core::ops::drop::Drop>::drop::h4a8efc8f09d53382
  19:     0xaaaab2e4706f - <alloc::sync::Arc<T>>::drop_slow::hc2ea343ad2f93ac0
  20:     0xaaaab2e5854b - core::ptr::drop_in_place::hb6353b2bc96db78a
  21:     0xaaaab2e40073 - <alloc::sync::Arc<T>>::drop_slow::h2dea5e573ca66a3e
  22:     0xaaaab2e3f00b - <alloc::sync::Arc<T>>::drop_slow::h162a3f09d3ba0300
  23:     0xaaaab2e3df67 - <alloc::sync::Arc<T>>::drop_slow::h079db1eaa8e3b0db
  24:     0xaaaab302034b - <std::collections::hash::table::RawTable<K, V> as core::ops::drop::Drop>::drop::h82577b4b7a0b7ecf
  25:     0xaaaab2e47b77 - <alloc::sync::Arc<T>>::drop_slow::hd192fd627b6ee25c
  26:     0xaaaab2d0cd2f - core::ptr::drop_in_place::had406d9151cad155
  27:     0xaaaab2d4205f - <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::hcbfac0e15ce98854
  28:     0xaaaab2d19167 - <futures::future::chain::Chain<A, B, C>>::poll::h538e63a3ffff2a60
  29:     0xaaaab2d798af - <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll::h32085e142563cdb8
  30:     0xaaaab3cadfe7 - futures::task_impl::std::set::h0b11e38022b9ad73
  31:     0xaaaab3cb1857 - std::panicking::try::do_call::hddd8be9cf26a7dfd
  32:     0xaaaab3e6079f - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:103
  33:     0xaaaab3cb02eb - tokio_threadpool::task::Task::run::h5db3ee2ffd393379
  34:     0xaaaab3ca9413 - tokio_threadpool::worker::Worker::run_task::h171907d3bd9c9f12
  35:     0xaaaab3ca86bb - tokio_threadpool::worker::Worker::run::h4312621f15e49a62
  36:     0xaaaab3c8b037 - <std::thread::local::LocalKey<T>>::with::h72daeae056824f0b
  37:     0xaaaab3c8b163 - <std::thread::local::LocalKey<T>>::with::h8c8555b94b2800da
  38:     0xaaaab3c8b847 - <std::thread::local::LocalKey<T>>::with::hf88440705c285496
  39:     0xaaaab3c8d17b - tokio::runtime::builder::Builder::build::{{closure}}::h9f9dd8752739a31b
  40:     0xaaaab3caf493 - <std::thread::local::LocalKey<T>>::with::ha0dde08f3d41c8f6
  41:     0xaaaab3caed4b - <std::thread::local::LocalKey<T>>::with::h0780676bfe6ec916
  42:     0xaaaab3cb13cf - std::sys_common::backtrace::__rust_begin_short_backtrace::h19faa807d4de2595
  43:     0xaaaab3cb17cf - std::panicking::try::do_call::h588d848c812046ed
  44:     0xaaaab3e6079f - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:103
  45:     0xaaaab3cada7f - <F as alloc::boxed::FnBox<A>>::call_box::hbd7a93ea0ef7f09c
  46:     0xaaaab3e556ef - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h85424732c346e3af
                        at liballoc/boxed.rs:656
                         - std::sys_common::thread::start_thread::h41cf1ad8630babd4
                        at libstd/sys_common/thread.rs:24
  47:     0xaaaab3e43f9b - std::sys::unix::thread::Thread::new::thread_start::hbd34cf20156b5b37
                        at libstd/sys/unix/thread.rs:90
  48:     0xffffbb05bfc3 - start_thread

Thread 'jsonrpc-eventloop-0' panicked at 'Propagating verifier thread panic on shutdown: Any', libcore/result.rs:1009

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new
```

**Comment by niklasad1** [comment]
/cc @andresilva shouldn't the light client use `is_epoch_end_light`?

According to the backtrace `is_epoch_end` is called, https://github.com/paritytech/parity-ethereum/blob/master/ethcore/src/engines/authority_round/mod.rs#L1411
