### ISSUE TITLE
Thread 'IO Worker #1' panicked at 'db get failed'

### ISSUE THREAD

**Issue by vkachan** [paritytech/parity-ethereum#10308]
- Parity Ethereum version: 2.3.2, 2.2.9
- Operating system: CentOS 7
- Installation: built from source
- Fully synchronized: no
- Network: ethereum
- Restarted: yes

Might be duplicate of this one [9864](https://github.com/paritytech/parity-ethereum/issues/9864) but not sure.

During the sync I see messages like:

```
2019-02-07 00:00:56  Imported #7185309 0xa128…5a40 (140 txs, 8.00 Mgas, 308 ms, 26.09 KiB)
2019-02-07 00:01:00  Error serving connection: Error { kind: BodyWrite, cause: Some(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }) }
2019-02-07 00:01:01  Error serving connection: Error { kind: BodyWrite, cause: Some(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }) }
2019-02-07 00:01:04  Error serving connection: Error { kind: BodyWrite, cause: Some(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }) }
2019-02-07 00:01:05  Error serving connection: Error { kind: Service, cause: Some(Error { kind: Body, cause: Some(Custom { kind: UnexpectedEof, error: IncompleteBody }) }) }
2019-02-07 00:01:09  Error serving connection: Error { kind: Service, cause: Some(Error { kind: Body, cause: Some(Custom { kind: UnexpectedEof, error: IncompleteBody }) }) }
20
```

And after a while parity going off after with the stacktrace:

```
====================

stack backtrace:
   0:     0x5596e0c0a6dd - backtrace::backtrace::trace::h6a895d5d279a8d2f
   1:     0x5596e0c098f2 - <backtrace::capture::Backtrace as core::default::Default>::default::h03a8d770395d927e
   2:     0x5596e0c09969 - backtrace::capture::Backtrace::new::h2eb1c11c92f206be
   3:     0x5596e0c08aa6 - panic_hook::gen_panic_msg::h0d1944a863be6686
   4:     0x5596df428788 - panic_hook::set_with::{{closure}}::h542ff047c4eda6f5
   5:     0x5596e0c829e6 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   6:     0x5596e0c82531 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   7:     0x5596e0c82415 - rust_begin_unwind
                        at libstd/panicking.rs:325
   8:     0x5596e0ccbfac - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   9:     0x5596e0334c39 - core::result::unwrap_failed::h2399773a2590e03c
  10:     0x5596e0194300 - ethcore::db::Readable::read_with_cache::h5037773446557c0c
  11:     0x5596e020069a - <ethcore::blockchain::blockchain::BlockChain as ethcore::blockchain::blockchain::BlockProvider>::transaction_address::hdd557808164548e3
  12:     0x5596e0171fd8 - ethcore::client::client::Client::transaction_address::hb8651b176b19ae5c
  13:     0x5596e01be5f8 - <ethcore_miner::pool::verifier::Verifier<C, ethcore_miner::pool::scoring::NonceAndGasPrice, ethcore_miner::pool::VerifiedTransaction> as transaction_pool::verifier::Verifier<ethcore_miner::pool::verifier::Transaction>>::verify_transaction::h1ba2b9c1d86b3e1d
  14:     0x5596e03ca944 - <core::iter::Map<I, F> as core::iter::iterator::Iterator>::fold::he2085efaf5d46a15
  15:     0x5596e035d94e - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter::h496e650c313a763c
  16:     0x5596e014c1f3 - ethcore_miner::pool::queue::TransactionQueue::import::hd5c8dffffec1b0e2
  17:     0x5596e03d2a84 - ethcore::client::client::IoChannelQueue::queue::{{closure}}::hbed2badb29c70796
  18:     0x5596dfe29389 - <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message::h2bc81d8d40ce8247
  19:     0x5596dfe200b3 - ethcore_io::worker::Worker::work_loop::hd8ed15b29bc31ae6
  20:     0x5596dfe049e2 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha1c547a9208bd140
  21:     0x5596dfe07466 - std::panicking::try::do_call::hb8749cd8d0dba258
  22:     0x5596e0c94bc9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  23:     0x5596dfe0cc27 - <F as alloc::boxed::FnBox<A>>::call_box::h252166b851e855b4
  24:     0x5596e0c7ee7d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  25:     0x5596e0c69a35 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  26:     0x7f8569ba9dd4 - start_thread
  27:     0x7f85696bceac - __clone
  28:                0x0 - <unknown>

Thread 'IO Worker #1' panicked at 'db get failed, key: [2, 95, 76, 163, 12, 1, 21, 183, 242, 193, 149, 87, 193, 191, 119, 39, 87, 191, 168, 87, 125, 245, 35, 199, 64, 4, 190, 128, 220, 209, 76, 220, 251]: Custom { kind: Other, error: StringError("IO error: While open a file for random read: /home/parity/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/323110.sst: Too many open files") }', libcore/result.rs:1009

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new
```

**Comment by joshua-mir** [comment]
> Too many open files

Can you share what type of storage you have on this machine?

**Comment by vkachan** [comment]
We we've got dedicated physical machine Intel G5500, 16GB, 1x 1TB SSD.

**Comment by joshua-mir** [comment]
Your earlier errors also point towards hardware instability - just to rule that out, could you try to run memory and disk integrity checks?

**Comment by joshua-mir** [comment]
Possibly related: #9102

**Comment by vkachan** [comment]
@joshua-mir just did the test of the hardware. It's 100% healthy ssd and memory. Got some inside info over the ssd whilst test :

```
=== START OF INFORMATION SECTION ===
Model Family:     OCZ/Toshiba Trion SSDs
Device Model:     OCZ-TRION100
Serial Number:    75EB60TIKMGX
LU WWN Device Id: 5 e83a97 200264f05
Firmware Version: SAFM11.2
User Capacity:    960,197,124,096 bytes [960 GB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    Solid State Device
Form Factor:      2.5 inches
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ACS-2 (minor revision not indicated)
SATA Version is:  SATA 3.1, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Thu Feb  7 11:31:15 2019 CET
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED
```

Maybe that might help to figure out.

**Comment by vkachan** [comment]
Does not occur anymore. I think issue can be closed for now.
