### ISSUE TITLE
Crash under docker - DB Corrupted

### ISSUE THREAD

**Issue by MatthewDarnell** [paritytech/parity-ethereum#10465]
- **Parity Ethereum version**: 2.4.0
- **Operating system**: Linux (Running Docker)
- **Installation**:docker
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

My docker compose file:

```services:
  parity:
    image: parity/parity:v2.4.0
    restart: always
    command: >
               --base-path /root/.parity
               --no-jsonrpc
               --db-compaction ssd
               --cache-size 4096
               --min-peers 50
               --max-peers 200
               --ws-interface all
               --ws-origins 127.0.0.1
```

I got a crash with this log:

```parity_1  | Thread 'Verifier #0' panicked at 'DB flush failed.: Custom { kind: Other, error: StringError("Corruption: block checksum mismatch: expected 1952717383, got 3037448460  in /root/.parity/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/492724.sst offset 32162372 size 30553") }', src/libcore/result.rs:1009
parity_1  | 
parity_1  | This is a bug. Please report it at:
parity_1  | 
parity_1  |     https://github.com/paritytech/parity-ethereum/issues/new
parity_1  | 
parity_1  | 2019-03-11 01:36:20 UTC Finishing work, please wait...
parity_1  | 2019-03-11 01:36:20 UTC   21/50 peers    282 MiB chain  626 MiB db  0 bytes queue   94 KiB sync  RPC:  3 conn,  120 req/s,  160 µs
parity_1  | 2019-03-11 01:36:20 UTC   21/50 peers    282 MiB chain  626 MiB db   78 KiB queue   94 KiB sync  RPC:  3 conn,  120 req/s,  160 µs
parity_1  | 2019-03-11 01:36:20 UTC   21/50 peers    282 MiB chain  626 MiB db   78 KiB queue   94 KiB sync  RPC:  3 conn,  120 req/s,  160 µs
parity_1  | 2019-03-11 01:36:20 UTC DB corrupted: Corruption: block checksum mismatch: expected 1952717383, got 3037448460  in /root/.parity/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/492724.sst offset 32162372 size 30553. Repair will be triggered on next restart
parity_1  | 2019-03-11 01:36:21 UTC DB corrupted: Corruption: block checksum mismatch: expected 1952717383, got 3037448460  in /root/.parity/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/492724.sst offset 32162372 size 30553. Repair will be triggered on next restart
parity_1  | 
parity_1  | 
parity_1  | ====================
parity_1  | 
parity_1  | stack backtrace:
parity_1  |    0:     0x561ebdfe3c7d - <no info>
parity_1  |    1:     0x561ebdfe2da2 - <no info>
parity_1  |    2:     0x561ebdfe1f56 - <no info>
parity_1  |    3:     0x561ebc77c168 - <no info>
parity_1  |    4:     0x561ebe0540e9 - <no info>
parity_1  |    5:     0x561ebe053b91 - <no info>
parity_1  |    6:     0x561ebe053a75 - <no info>
parity_1  |    7:     0x561ebe0716ec - <no info>
parity_1  |    8:     0x561ebcf62b60 - <no info>
parity_1  |    9:     0x561ebccd6f22 - <no info>
parity_1  |   10:     0x561ebccd9fd4 - <no info>
parity_1  |   11:     0x561ebccc3461 - <no info>
parity_1  |   12:     0x561ebccb9106 - <no info>
parity_1  |   13:     0x561ebc77742e - <no info>
parity_1  |   14:     0x561ebc779d71 - <no info>
parity_1  |   15:     0x561ebc67c802 - <no info>
parity_1  |   16:     0x561ebe053a12 - <no info>
parity_1  |   17:     0x561ebe06ab99 - <no info>
parity_1  |   18:     0x561ebe0544a3 - <no info>
parity_1  |   19:     0x561ebc77a6e1 - <no info>
parity_1  |   20:     0x7f7bfe35982f - <no info>
parity_1  |   21:     0x561ebc5d4c38 - <no info>
parity_1  |   22:                0x0 - <no info>
parity_1  | 
parity_1  | Thread 'main' panicked at 'Propagating verifier thread panic on shutdown: Any', src/libcore/result.rs:1009
parity_1  | 
parity_1  | This is a bug. Please report it at:
parity_1  | 
parity_1  |     https://github.com/paritytech/parity-ethereum/issues/new
parity_1  | 
parity_parity_1 exited with code 1
```

Upon restarting:

```# tail -f nohup.out
Creating network "parity_default" with the default driver
Creating parity_parity_1 ... done
Attaching to parity_parity_1
parity_1  | 2019-03-12 01:25:21 UTC Starting Parity-Ethereum/v2.4.0-beta-c7d8ee1-20190227/x86_64-linux-gnu/rustc1.32.0
parity_1  | 2019-03-12 01:25:21 UTC Keys path /root/.parity/keys/ethereum
parity_1  | 2019-03-12 01:25:21 UTC DB path /root/.parity/chains/ethereum/db/906a34e69aec8c0d
parity_1  | 2019-03-12 01:25:21 UTC State DB configuration: fast
parity_1  | 2019-03-12 01:25:21 UTC Operating mode: active
parity_1  | 2019-03-12 01:25:21 UTC DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col1, col3, col0, col2, attempting repair
```

My disk is not out of space, I have it mounted into the image:

```# df -h /mnt/volume/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda        148G   84G   57G  60% /mnt/volume```

**Comment by joshua-mir** [comment]
DB corruption errors are usually random or a sign of a hardware error or unclean shutdown unfortunately, there isn't really anything that we can do about it, and it likely requires a fresh resync.

**Comment by MatthewDarnell** [comment]
Parity has now become unusable. Every day or so, a crash. This time it was this:

```parity_1  | Thread 'jsonrpc-eventloop-1' panicked at 'Propagating verifier thread panic on shutdown: Any', src/libcore/result.rs:1009
parity_1  | 
parity_1  | This is a bug. Please report it at:
parity_1  | 
parity_1  |     https://github.com/paritytech/parity-ethereum/issues/new```

**Comment by MatthewDarnell** [comment]
And a few days ago:

```root@eth-parity-docker-s-2vcpu-2gb-nyc3-01:~/parity# tail -f nohup.out 
parity_1  | Thread 'IO Worker #1' panicked at 'DB flush failed.: Custom { kind: Other, error: StringError("Corruption: block checksum mismatch: expected 3611182791, got 3296939960  in /root/.parity/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/027765.sst offset 26906610 size 26074") }', src/libcore/result.rs:1009
parity_1  | 
parity_1  | This is a bug. Please report it at:
parity_1  | 
parity_1  |     https://github.com/paritytech/parity-ethereum/issues/new
parity_1  | 
parity_1  | 2019-03-17 08:44:37 UTC DB corrupted: Corruption: block checksum mismatch: expected 3611182791, got 3296939960  in /root/.parity/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/027765.sst offset 26906610 size 26074. Repair will be triggered on next restart
parity_1  | 2019-03-17 08:44:37 UTC DB corrupted: Corruption: block checksum mismatch: expected 3611182791, got 3296939960  in /root/.parity/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/027765.sst offset 26906610 size 26074. Repair will be triggered on next restart
parity_parity_1 exited with code 1```

I ran this node for months with 0 problems before updating to 2.4.0

**Comment by joshua-mir** [comment]
Unfortunately it looks like resyncing is probably the only option at this point, if you attempt to resync and you are still seeing similar issues, I would seriously consider checking your hardware integrity.

**Comment by MatthewDarnell** [comment]
I am running on a Digital Ocean VPS. ` 8 GB Memory / 60 GB Disk + 150 GB / Ubuntu Docker 17.12.0~ce on 16.04`

I had a 150GB DO volume mounted for the chain data, and yesterday I created a brand new volume and it automatically mounted into the vps.

```
parity_1  | 2019-03-19 15:02:31 UTC Imported #7399921 0x40a8…0f09 (212 txs, 7.99 Mgas, 2169 ms, 33.64 KiB)
parity_1  | 2019-03-19 15:02:38 UTC Imported #7399922 0xa4ca…4b32 (37 txs, 7.98 Mgas, 1456 ms, 26.13 KiB)
parity_1  | 2019-03-19 15:02:38 UTC DB corrupted: Corruption: bad entry in block. Repair will be triggered on next restart
parity_1  | 
parity_1  | 
parity_1  | ====================
parity_1  | 
parity_1  | stack backtrace:
...
parity_1  |   21:                0x0 - <no info>
parity_1  | 
parity_1  | Thread 'Verifier #2' panicked at 'DB flush failed.: Custom { kind: Other, error: StringError("Corruption: bad entry in block") }', src/libcore/result.rs:1009
parity_1  | 
parity_1  | This is a bug. Please report it at:
parity_1  | 
parity_1  |     https://github.com/paritytech/parity-ethereum/issues/new
parity_1  | 
parity_1  | 2019-03-19 15:02:39 UTC Finishing work, please wait...
parity_1  | 2019-03-19 15:02:46 UTC   #4854904   30/50 peers    165 MiB chain  206 MiB db  0 bytes queue  187 MiB sync  RPC:  2 conn,   19 req/s,  306 µs
parity_1  | 2019-03-19 15:02:46 UTC   #4854904   30/50 peers    311 MiB chain  206 MiB db  0 bytes queue  187 MiB sync  RPC:  2 conn,   19 req/s,  306 µs
parity_1  | 2019-03-19 15:03:24 UTC DB corrupted: Corruption: bad entry in block. Repair will be triggered on next restart
parity_1  | 2019-03-19 15:03:25 UTC DB corrupted: Corruption: bad entry in block. Repair will be triggered on next restart
parity_1  | 
parity_1  | 
parity_1  | ====================
parity_1  | 
parity_1  | stack backtrace:
...
parity_1  |   22:                0x0 - <no info>
parity_1  | 
parity_1  | Thread 'main' panicked at 'Propagating verifier thread panic on shutdown: Any', src/libcore/result.rs:1009
parity_1  | 
parity_1  | This is a bug. Please report it at:
parity_1  | 
parity_1  |     https://github.com/paritytech/parity-ethereum/issues/new
parity_1  | 
parity_parity_1 exited with code 1
```

**Comment by MatthewDarnell** [comment]
```
# cat docker-compose.yml 
version: '2'

services:
  parity:
    image: parity/parity:v2.4.0
    restart: always
    command: >
               --base-path /root/.parity
               --no-jsonrpc
               --db-compaction ssd
               --cache-size 4096
               --min-peers 50
               --max-peers 200
               --ws-interface all
               --ws-origins 127.0.0.1
    ports:
      - "8546:8546"
      - "30303:30303"
    user: root
    volumes:
      - /mnt/ethereum:/root/.parity:rw
volumes:
  ethereum-data:
```

**Comment by MatthewDarnell** [comment]
Have tried 2.3.5 all the way to 2.4.2, all are crashing after 24 hours or so.

**Comment by MatthewDarnell** [comment]
Ok, I have set up parity 2.4.3 (with the exact same docker-compose.yml file) on a new Digital Ocean VPS, with better specs (32GB ram), and it seems to have been running totally fine for the past few days. Not sure what is going on here, but possibly it is indeed a hardware issue. Closing this issue.
