### ISSUE TITLE
Cannot increase the gasPrice of a pending transaction: "There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee."

### ISSUE THREAD

**Issue by palkeo** [paritytech/parity-ethereum#10636]
Hi,

- **Parity Ethereum version**: 0.0.0
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: yes
- **Network**: ethereum

If I send a first transaction with nonce A. Then I send another transaction with the same nonce A, and a higher gasPrice, and Parity gives me this error:
```There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee.```

Note that I tried with a fee twice as big as the first transaction. I know this wouldn't work if the gasPrice is not at least 12.5% higher than the old transaction.

If I inspect the local transactions, I get this:
```
    "A": {
      "status": "mined",
      "transaction": {
        ...
        "gasPrice": "0x2c4d6f535",
        "hash": "A",
        "nonce": "0xad0",
        ...
      },
    "B": {
      "error": "[B] too cheap to enter the pool. Min score: 0xb2d05e00",
      "status": "rejected",
      "transaction": {
        ...
        "gasPrice": "0x7850fb48e",
        "hash": "B",
        "nonce": "0xad0",
        ...
      }
    }
```

My understanding in that the "score" is the gas price? Here it clearly says "too cheap to enter the pool" even if my gasPrice is actually above the min score it shows.
Plus, this is a local transaction so it should get included anyway, from my understanding.

Note that no other transactions were sent previously from my node. So it's impossible that I'm sending too much transactions somehow.

Also note that the second transaction, B, was sent a few seconds after A, so at that time A was not yet mined and B should have been able to replace it.

**Comment by joshua-mir** [comment]
Score is not equivalent to gasPrice (but gasPrice is used to calculate score, along with where the transaction came from, ie txpool or rpc, and the sender)

**Comment by palkeo** [comment]
Ok for the score, if you have an explanation of how it's computed I'm interested.

As for the problem, the doc says it can be replaced if the fee increase by >12.5%.  As I said I tried doubling the tx fee, and it's still not enough. In my example with the local transaction, I also increase it by more than that. That's why it doesn't seem consistent to me.

**Comment by devilrayzl** [comment]
Same problem and I tried to increase  gasPrice to 30GWEI, it still not work.

**Comment by joshua-mir** [comment]
@devilrayzl can you share what version you are running? We've had a few fixes that may have addressed this (which should be available in the latest stable branch)

**Comment by devilrayzl** [comment]
Sure.
**version Parity-Ethereum/v2.5.7-stable-6bd7db9-20190829/x86_64-linux-gnu/rustc1.36.0**

**Comment by gituser** [comment]
I have this issue as well. Why it's not fixed yet?

Happens on the `parity-v2.5.7-stable-6bd7db9-20190829` when you try to send transaction with previously used `nonce` (e.g. `nonce: 0x0`) parity errors out:

```
There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee.
    at web3.js:3119:20
    at web3.js:6023:15
    at web3.js:4995:36
    at <anonymous>:1:1
```

**Comment by joshua-mir** [comment]
Thanks for the report, the additional specificity you've provided may help.

**Comment by garywu921207** [comment]
I have this issue as well. but i don't know is it a bug or i send the transaction wrong?

**Comment by dvdplm** [comment]
We recently merged https://github.com/paritytech/parity-ethereum/pull/11086 which could be related to this. It is not in any of the releases yet, but if anyone here has the time to compile from master it would be good to see if the issue is solved.

**Comment by gituser** [comment]
@dvdplm parity also errors out with this when trying to replace existing transaction with `nonce: 0x0` (happens on the latest stable `parity-v2.5.9-stable`:

```
Transaction nonce is too low. Try incrementing the nonce.
    at web3.js:3119:20
    at web3.js:6023:15
    at web3.js:4995:36
    at <anonymous>:1:1
```

**Comment by or2008** [comment]
have the same issue on version 3.0.1.. any updates?
