### ISSUE TITLE
Corruption: block checksum mismatch: expected 2619177551, got 3305970101

### ISSUE THREAD

**Issue by ksolo** [paritytech/parity-ethereum#10885]
Hello there!

I'm running Parity 2.5.5 stable on MacOS Mojave (10.14.5) and am having problems with the initial sync.

I have deleted the db a few times using `parity db kill` and restarted the processes and each time hitting a checksum mismatch error

```
Corruption: block checksum mismatch: expected 2619177551, got 3305970101
```

The logs:

```
$ parity
2019-07-14 15:44:20  Starting Parity-Ethereum/v2.5.5-stable-3ebc76975-20190708/x86_64-macos/rustc1.36.0
2019-07-14 15:44:20  Keys path /Users/ksolo/Library/Application Support/io.parity.ethereum/keys/ethereum
2019-07-14 15:44:20  DB path /Users/ksolo/Library/Application Support/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
2019-07-14 15:44:20  State DB configuration: fast
2019-07-14 15:44:20  Operating mode: active
2019-07-14 15:44:20  Configured for Ethereum using Ethash engine
2019-07-14 15:44:21  Listening for new connections on 127.0.0.1:8546.
2019-07-14 15:44:21  Removed existing file '/Users/ksolo/Library/Application Support/io.parity.ethereum/jsonrpc.ipc'.
2019-07-14 15:44:21  Updated conversion rate to Ξ1 = US$237.51 (20049282 wei/gas)
2019-07-14 15:44:26  Snapshot initializing (8 chunks restored)        #0   11/25 peers   920 bytes chain 512 KiB db 0 bytes queue 8 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:44:26  Public node URL: enode://9d94748ce70bdce432990f1f6c1ff523ca45504166cdff3f522ff80506e0a9679ac9d70907c1d49e9f9cb16c6a3456365f37f2e03f8ab588730854fa74d45a20@10.91.107.192:30303
2019-07-14 15:44:31  Snapshot initializing (31 chunks restored)        #0   11/25 peers   920 bytes chain 512 KiB db 0 bytes queue 8 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:44:36  Snapshot initializing (54 chunks restored)        #0   11/25 peers   920 bytes chain 512 KiB db 0 bytes queue 8 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:44:41  Snapshot initializing (76 chunks restored)        #0   11/25 peers   920 bytes chain 512 KiB db 0 bytes queue 8 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:44:46  Snapshot initializing (100 chunks restored)        #0   11/25 peers   920 bytes chain 512 KiB db 0 bytes queue 8 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:44:51  Snapshot initializing (117 chunks restored)        #0   12/25 peers   920 bytes chain 512 KiB db 0 bytes queue 8 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:44:56  Snapshot initializing (143 chunks restored)        #0   13/25 peers   920 bytes chain 512 KiB db 0 bytes queue 8 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:45:01  Snapshot initializing (161 chunks restored)        #0   14/25 peers   920 bytes chain 512 KiB db 0 bytes queue 8 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:45:06  Syncing snapshot 179/3306        #0   16/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:45:11  Syncing snapshot 183/3306        #0   17/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:45:16  Syncing snapshot 190/3306        #0   17/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:45:21  Syncing snapshot 198/3306        #0   17/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:45:26  Syncing snapshot 204/3306        #0   18/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:45:31  Syncing snapshot 210/3306        #0   18/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:45:36  Syncing snapshot 217/3306        #0   18/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:45:41  Syncing snapshot 223/3306        #0   18/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:45:46  Syncing snapshot 230/3306        #0   18/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:45:51  Syncing snapshot 236/3306        #0   20/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:45:56  Syncing snapshot 242/3306        #0   20/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:46:01  Syncing snapshot 248/3306        #0   20/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:46:06  Syncing snapshot 254/3306        #0   20/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:46:11  Syncing snapshot 259/3306        #0   20/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:46:16  Syncing snapshot 265/3306        #0   20/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:46:21  Syncing snapshot 271/3306        #0   20/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:46:27  Syncing snapshot 277/3306        #0   20/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:46:31  Syncing snapshot 283/3306        #0   20/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:46:37  Syncing snapshot 292/3306        #0   20/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:46:42  Syncing snapshot 298/3306        #0   20/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:46:46  Syncing snapshot 304/3306        #0   20/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:46:51  Syncing snapshot 311/3306        #0   21/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:46:56  Syncing snapshot 317/3306        #0   21/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:47:01  Syncing snapshot 323/3306        #0   21/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:47:06  Syncing snapshot 326/3306        #0   21/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:47:11  Syncing snapshot 331/3306        #0   21/25 peers   920 bytes chain 512 KiB db 0 bytes queue 16 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-14 15:47:13  DB corrupted: Corruption: block checksum mismatch: expected 2619177551, got 3305970101  in /Users/ksolo/Library/Application Support/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/snapshot/restoration/db/001251.sst offset 51583691 size 16370. Repair will be triggered on next restart
2019-07-14 15:47:13  Encountered error during snapshot restoration: Corruption: block checksum mismatch: expected 2619177551, got 3305970101  in /Users/ksolo/Library/Application Support/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/snapshot/restoration/db/001251.sst offset 51583691 size 16370
```

At this point everything appears to be frozen and I have to kill the process.

**Comment by joshua-mir** [comment]
@ksolo it looks like a peer is giving you a corrupt warp snapshot - if you see this repeatedly, I would consider deleting the `nodes.json` file in your `DATADIR/chains/ethereum/network` or maybe messing around with the `--warp-barrier` to avoid getting snapshots from that peer.

**Comment by ordian** [comment]
Looks like a low-level disk/RocksDB failure.
AFAIK, `parity db kill` doesn't delete the snapshot folder, so you could try removing it manually
(in your case it's `/Users/ksolo/Library/Application Support/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/snapshot`).

**Comment by ksolo** [comment]
@joshua-mir @ordian Thanks for getting back to me! I'll try these suggestions and run it again.

**Comment by gituser** [comment]
I just had a crash with DB corrupted on `v2.5.5` too.

And parity isn't restoring anything it's simply stuck in limbo and requires full resync. Super annoying.

I don't see any errors in dmesg or anywhere else about failed sectors on my NVME drives, so it has to be something to do with parity:

```
2019-07-16 03:41:11  Verifier #0 WARN kvdb_rocksdb  DB corrupted: Corruption: bad entry in block. Repair will be triggered on next restart


====================

stack backtrace:
   0:     0x563ac446e1ed - backtrace::backtrace::trace::h3b13a3b0bfa8fe24
   1:     0x563ac446b2be - panic_hook::gen_panic_msg::hb3f9980518fbc3e8
   2:     0x563ac4584af7 - panic_hook::set_with::{{closure}}::h2ef65aa679d4a524
   3:     0x563ac44afd04 - std::panicking::rust_panic_with_hook::h057ff03eb4c8000f
                        at src/libstd/panicking.rs:478
   4:     0x563ac44afa7e - std::panicking::continue_panic_fmt::ha6d6ae144369025b
                        at src/libstd/panicking.rs:381
   5:     0x563ac44cc5b5 - rust_begin_unwind
                        at src/libstd/panicking.rs:308
   6:     0x563ac44d250b - core::panicking::panic_fmt::hc4f83bfed80aeabd
                        at src/libcore/panicking.rs:85
   7:     0x563ac41f2686 - core::result::unwrap_failed::h1da4e2a190b03633
   8:     0x563ac3f5776d - ethcore::client::client::Importer::import_verified_blocks::hdb8a24774fb46554
   9:     0x563ac3809281 - <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message::h638abf17257bd545
  10:     0x563ac3d406a9 - ethcore_io::service_mio::IoChannel<Message>::send_sync::h2f200202ec2466bc
  11:     0x563ac3d1991b - ethcore::verification::queue::QueueSignal::set_sync::hda12cace25390049
  12:     0x563ac3d44ced - std::sys_common::backtrace::__rust_begin_short_backtrace::h8b4c2a14eebf2bf4
  13:     0x563ac3dcd104 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h6babe2e56d3b5a8d
  14:     0x563ac44cb33e - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h805c3cc89d534c05
                        at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
  15:     0x563ac44cde9b - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h9ebda9db5f03daf3
                        at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
                         - std::sys_common::thread::start_thread::ha32838ccbb8a8179
                        at src/libstd/sys_common/thread.rs:13
                         - std::sys::unix::thread::Thread::new::thread_start::h6f10b78f26c98dc6
                        at src/libstd/sys/unix/thread.rs:79
  16:     0x7f3960e3c063 - start_thread
  17:     0x7f396095b62c - clone
  18:                0x0 - <unknown>

Thread 'Verifier #0' panicked at 'DB flush failed.: Custom { kind: Other, error: StringError("Corruption: bad entry in block") }', src/libcore/result.rs:999

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new


2019-07-16 03:41:11  main INFO parity_ethereum::run  Finishing work, please wait...
2019-07-16 03:41:12  IO Worker #1 WARN kvdb_rocksdb  DB corrupted: Corruption: bad entry in block. Repair will be triggered on next restart
2019-07-16 03:41:14  jsonrpc-eventloop-0 WARN shutdown  unable to get mut ref for engine for shutdown.


====================

stack backtrace:
   0:     0x563ac446e1ed - backtrace::backtrace::trace::h3b13a3b0bfa8fe24
   1:     0x563ac446b2be - panic_hook::gen_panic_msg::hb3f9980518fbc3e8
   2:     0x563ac4584af7 - panic_hook::set_with::{{closure}}::h2ef65aa679d4a524
   3:     0x563ac44afd04 - std::panicking::rust_panic_with_hook::h057ff03eb4c8000f
                        at src/libstd/panicking.rs:478
   4:     0x563ac44afa7e - std::panicking::continue_panic_fmt::ha6d6ae144369025b
                        at src/libstd/panicking.rs:381
   5:     0x563ac44cc5b5 - rust_begin_unwind
                        at src/libstd/panicking.rs:308
   6:     0x563ac44d250b - core::panicking::panic_fmt::hc4f83bfed80aeabd
                        at src/libcore/panicking.rs:85
   7:     0x563ac47ce770 - core::result::unwrap_failed::h96bf7c627fd8285a
   8:     0x563ac47a7800 - <ethcore::verification::queue::VerificationQueue<K> as core::ops::drop::Drop>::drop::hdb58fbf8a0150d7e
   9:     0x563ac48a9400 - core::ptr::real_drop_in_place::h30eb7831c14ae48b.74788
  10:     0x563ac48a9131 - core::ptr::real_drop_in_place::h4d3e2bc2754f6d81.74767
  11:     0x563ac419ca1a - alloc::sync::Arc<T>::drop_slow::h002620ab4abf0bdc
  12:     0x563ac419ca1a - alloc::sync::Arc<T>::drop_slow::h002620ab4abf0bdc
  13:     0x563ac37484e4 - alloc::sync::Arc<T>::drop_slow::h33849f564b3a0419
  14:     0x563ac35f30da - core::ptr::real_drop_in_place::h96b851c9e7b38507
  15:     0x563ac419ca1a - alloc::sync::Arc<T>::drop_slow::h002620ab4abf0bdc
  16:     0x563ac452836e - alloc::sync::Arc<T>::drop_slow::hb49f61fd79773c0d
  17:     0x563ac419ca1a - alloc::sync::Arc<T>::drop_slow::h002620ab4abf0bdc
  18:     0x563ac404cb9c - core::ptr::real_drop_in_place::h30a1235cffa36a64
  19:     0x563ac4526d03 - alloc::sync::Arc<T>::drop_slow::h70b744b231a7451e
  20:     0x563ac46f7625 - core::ptr::real_drop_in_place::habae2440e7bc2b3c
  21:     0x563ac486192b - <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll::h9718e8ab5c38deb3
  22:     0x563ac43620ff - futures::task_impl::std::set::h78da85acf379b616
  23:     0x563ac435fff2 - tokio_threadpool::worker::Worker::run_task::h8707b008c521fd33
  24:     0x563ac435e0c2 - tokio_threadpool::worker::Worker::run::hc14a9b13d6edffae
  25:     0x563ac434408e - tokio::runtime::builder::Builder::build::{{closure}}::h2ce8ae50d62f213e
  26:     0x563ac43626fb - std::sys_common::backtrace::__rust_begin_short_backtrace::h9468191d4a2bdecf
  27:     0x563ac4360d4f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h55d0c5125eea3ba0
  28:     0x563ac44cb33e - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h805c3cc89d534c05
                        at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
  29:     0x563ac44cde9b - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h9ebda9db5f03daf3
                        at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
                         - std::sys_common::thread::start_thread::ha32838ccbb8a8179
                        at src/libstd/sys_common/thread.rs:13
                         - std::sys::unix::thread::Thread::new::thread_start::h6f10b78f26c98dc6
                        at src/libstd/sys/unix/thread.rs:79
  30:     0x7f3960e3c063 - start_thread
  31:     0x7f396095b62c - clone
  32:                0x0 - <unknown>

Thread 'jsonrpc-eventloop-0' panicked at 'Propagating verifier thread panic on shutdown: Any', src/libcore/result.rs:999

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new


2019-07-16 03:41:14  jsonrpc-eventloop-0 WARN kvdb_rocksdb  DB corrupted: Corruption: bad entry in block. Repair will be triggered on next restart
```

**Comment by joshua-mir** [comment]
@gituser could you please make a new issue for that? It doesn't appear to be related to this issue.

**Comment by gituser** [comment]
@joshua-mir update my comment with issue link.

**Comment by ksolo** [comment]
@joshua-mir @ordian I removed the files and things are moving further along. I'll close this issue. Thanks for the help!
