### ISSUE TITLE
Thread 'jsonrpc-eventloop-0' panicked at 'Unable to determine socket peer address:

### ISSUE THREAD

**Issue by Parean** [paritytech/parity-ethereum#11169]
- **Parity Ethereum version**: 2.4.6
- **Operating system**:  Linux
- **Installation**:  built from source
- **Fully synchronized**:  yes
- **Network**: ethereum 
- **Restarted**: yes

Launch parity with the following parameters:

```
./parity --port {port} --jsonrpc-interface={ip} --jsonrpc-port={port} --ws-port={port} --jsonrpc-apis=safe,parity_set --jsonrpc-hosts=all --allow-ips=public --max-peers=256 --max-pending-peers=256 --db-path={path} --tracing on
```
Periodically, it crashes for an incomprehensible reason to me. Here is the backtrace:

```
   0:     0x556d65f7486d - backtrace::backtrace::trace::h30c5c6ad32c7dab5
   1:     0x556d65f73a82 - <backtrace::capture::Backtrace as core::default::Default>::default::h83646577e299f574
   2:     0x556d65f72bf6 - panic_hook::gen_panic_msg::h706e242ecd0a2981
   3:     0x556d64a863a8 - panic_hook::set_with::{{closure}}::hd2d2338cfd316431
   4:     0x556d65fe2005 - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                        at src/libstd/panicking.rs:481
   5:     0x556d65fe1aa1 - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                        at src/libstd/panicking.rs:384
   6:     0x556d65fe1985 - rust_begin_unwind
                        at src/libstd/panicking.rs:311
   7:     0x556d6600563c - core::panicking::panic_fmt::h7e9f94035af782b3
                        at src/libcore/panicking.rs:85
   8:     0x556d66005736 - core::result::unwrap_failed::hf7591c1dd9412006
                        at src/libcore/result.rs:1084
   9:     0x556d65ac1cc7 - <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll::hd30b2c522cc9466c
  10:     0x556d65ab2af8 - <futures::future::select::Select<A,B> as futures::future::Future>::poll::hf10b1bb04e407b6c
  11:     0x556d65ac01c0 - <futures::future::map::Map<A,F> as futures::future::Future>::poll::ha43211e773dc26a0
  12:     0x556d65a9edeb - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::hacb956317c305448
  13:     0x556d65a9ba34 - <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll::h3499e967dfd882f4
  14:     0x556d65e30691 - futures::task_impl::std::set::h74db2fd876947b73
  15:     0x556d65e302f1 - std::panicking::try::do_call::had9faf0535c97878
  16:     0x556d65fecf79 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:80
  17:     0x556d65e31228 - tokio_threadpool::task::Task::run::h98260510dc83cff5
  18:     0x556d65e29bd5 - tokio_threadpool::worker::Worker::run_task::h71021f86ffb7780e
  19:     0x556d65e28cf9 - tokio_threadpool::worker::Worker::run::hec0bb1a707742ca7
  20:     0x556d65e088bf - std::thread::local::LocalKey<T>::with::hec729ed9ec999003
  21:     0x556d65e08125 - std::thread::local::LocalKey<T>::with::h03f46cb69c8cebb0
  22:     0x556d65e08350 - std::thread::local::LocalKey<T>::with::h2957357488a566ff
  23:     0x556d65e02bad - tokio::runtime::builder::Builder::build::{{closure}}::h22205d406db893da
  24:     0x556d65e2ef29 - std::thread::local::LocalKey<T>::with::h5f33506d8246b7c2
  25:     0x556d65e2ead8 - std::thread::local::LocalKey<T>::with::h56408f1944409e5b
  26:     0x556d65e2c0fa - std::sys_common::backtrace::__rust_begin_short_backtrace::hdc2343282b37cc74
  27:     0x556d65e3024b - std::panicking::try::do_call::h1738fcfc4a2218a2
  28:     0x556d65fecf79 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:80
  29:     0x556d65e2cdce - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1590075f6f0cc746
  30:     0x556d65fcdffe - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2877b2aefb0fd627
                        at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  31:     0x556d65fec29f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h13f473dbcdaa0fef
                        at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
                         - std::sys_common::thread::start_thread::h562a7c4953cb1d31
                        at src/libstd/sys_common/thread.rs:13
                         - std::sys::unix::thread::Thread::new::thread_start::h382c6ae14181d163
                        at src/libstd/sys/unix/thread.rs:79
  32:     0x7f16f6918181 - start_thread
  33:     0x7f16f6825b1e - __clone
  34:                0x0 - <unknown>

Thread 'jsonrpc-eventloop-0' panicked at 'Unable to determine socket peer address: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }', src/libcore/result.rs:1084
```

**Comment by dvdplm** [comment]
What is `{port}` set to? Are you using the same port for different network services perhaps?

```
./parity --port {port} --jsonrpc-interface={ip} --jsonrpc-port={port} --ws-port={port} --jsonrpc-apis=safe,parity_set --jsonrpc-hosts=all --allow-ips=public --max-peers=256 --max-pending-peers=256 --db-path={path} --tracing on
```

**Comment by Parean** [comment]
No, I use different ports.

**Comment by dvdplm** [comment]
Can you repeat this panic with stable/beta or master?

**Comment by seunlanlege** [comment]
The offending code, most likely the connection had already been dropped.

https://github.com/paritytech/jsonrpc/blob/44184766aeb59a95b4d6f4c7eaff0c9e1ef278eb/tcp/src/server.rs#L87-L93

i think it would be ideal ignore the connection instead of panicing

**Comment by niklasad1** [comment]
Should be fixed when https://github.com/paritytech/jsonrpc/pull/502 is merged
