### ISSUE TITLE
Thread 'http.worker10' panicked at 'decode db value failed: RlpExpectedToBeList'

### ISSUE THREAD

**Issue by androzd** [paritytech/parity-ethereum#11421]
- **Parity Ethereum version**: v2.7.0
- **Operating system**: Linux
- **Installation**: Downloaded from releases
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

Parity updated from previous stable version (v2.5.13)

Thread 'http.worker10' panicked at 'decode db value failed: RlpExpectedToBeList', src/libcore/result.rs:1165

Restarts does not helps, after restart syncing work 1-3 minutes and this error appeared again

**Comment by androzd** [comment]
After a multiple restarts its freezes without any messages

**Comment by dvdplm** [comment]
> after restart syncing work 1-3 minutes

Not sure I understand what you mean by this. Do you mean that syncing is making progress for a few minutes? You see new blocks get imported? 

Is the node receiving any RPC traffic? If yes, what kind of calls are you making?

**Comment by androzd** [comment]
After restart I got new blocks for 1-3 minutes
Node receiving many rpc requests (I scan blockchain for my deposits to multiple addresses)

**Comment by androzd** [comment]
Full log with error:

Loading config file from /home/eth/bin/config.toml
2020-01-29 16:37:20  Starting Parity-Ethereum/v2.7.0-stable-aa0a703-20200128/x86_64-unknown-linux-gnu/rustc1.40.0
2020-01-29 16:37:20  Keys path /home/eth/parity/keys/ethereum
2020-01-29 16:37:20  DB path /home/eth/parity/chains/ethereum/db/906a34e69aec8c0d
2020-01-29 16:37:20  State DB configuration: fast +Fat +Trace
2020-01-29 16:37:20  Operating mode: active
2020-01-29 16:37:20  Warning: Warp Sync is disabled because Fat DB is turned on.
2020-01-29 16:37:52  Configured for Ethereum using Ethash engine
2020-01-29 16:37:52  Running without a persistent transaction queue.
2020-01-29 16:37:53  Updated conversion rate to Ξ1 = US$175.38 (27151924 wei/gas)
2020-01-29 16:37:58  Public node URL: enode://77fb5569ea9982c9e6318337c8f7360861cdb60eef7335c487b70a9835dd2af3a77390cfe996b5254e5d6856e39218a9ae78f029c77c506827290c24636ecfd5@195.201.106.32:30303
2020-01-29 16:38:14  Imported #9377922 0x6585…348c (142 txs, 9.94 Mgas, 657 ms, 24.89 KiB) + another 2 block(s) containing 159 tx(s)
2020-01-29 16:38:22    17/100 peers   5 MiB chain 73 MiB db 0 bytes queue 4 MiB sync  RPC:  0 conn,    0 req/s,    0 µs
2020-01-29 16:38:31  Imported #9377923 0xd1f9…821e (149 txs, 9.89 Mgas, 697 ms, 24.40 KiB)
2020-01-29 16:38:36  Imported #9377924 0x256f…50c4 (29 txs, 2.21 Mgas, 276 ms, 6.60 KiB)
2020-01-29 16:38:52    23/100 peers   26 MiB chain 74 MiB db 0 bytes queue 7 MiB sync  RPC:  0 conn,    0 req/s,    0 µs
2020-01-29 16:38:58  Imported #9377925 0x7401…5aed (138 txs, 9.92 Mgas, 627 ms, 26.98 KiB)
2020-01-29 16:39:03  Imported #9377926 0x8127…6834 (126 txs, 9.94 Mgas, 448 ms, 24.97 KiB)
2020-01-29 16:39:17  Panic occurred, see stderr for details


====================

stack backtrace:
   0:     0x55e0e82f12ed - <no info>
   1:     0x55e0e8af7558 - <no info>
   2:     0x55e0e8d7d90a - <no info>
   3:     0x55e0e95b8a53 - <no info>
   4:     0x55e0e95b87dd - <no info>
   5:     0x55e0e95d3f55 - <no info>
   6:     0x55e0e83a9d3c - <no info>
   7:     0x55e0e83b00f5 - <no info>
   8:     0x55e0e8524baa - <no info>
   9:     0x55e0e8565298 - <no info>
  10:     0x55e0e8bea07a - <no info>
  11:     0x55e0e8e428d5 - <no info>
  12:     0x55e0e8b7c874 - <no info>
  13:     0x55e0e8d71ec0 - <no info>
  14:     0x55e0e8d57a72 - <no info>
  15:     0x55e0e8255d92 - <no info>
  16:     0x55e0e8e53a6f - <no info>
  17:     0x55e0e8e55803 - <no info>
  18:     0x55e0e8e55803 - <no info>
  19:     0x55e0e8e51f92 - <no info>
  20:     0x55e0e8ef183f - <no info>
  21:     0x55e0e8b6d754 - <no info>
  22:     0x55e0e8b85664 - <no info>
  23:     0x55e0e95fcb38 - <no info>
  24:     0x55e0e95f8445 - <no info>
  25:     0x55e0e95f680f - <no info>
  26:     0x55e0e95e29c6 - <no info>
  27:     0x55e0e95da6ea - <no info>
  28:     0x55e0e95f48bd - <no info>
  29:     0x55e0e95f5327 - <no info>
  30:     0x55e0e95d2b1e - <no info>
  31:     0x55e0e95d5b4f - <no info>
  32:     0x7f1d589d36da - <no info>
  33:     0x7f1d580d888e - <no info>
  34:                0x0 - <no info>

Thread 'http.worker10' panicked at 'decode db value failed: RlpExpectedToBeList', src/libcore/result.rs:1165

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new


2020-01-29 16:39:17  Finishing work, please wait...

**Comment by dvdplm** [comment]
> Node receiving many rpc requests (I scan blockchain for my deposits to multiple addresses)

Ok, this could be a bug in the RPC layer. What we need to make progress here is the logs from the RPC request that come in at the time of the panic. Turn on rpc logging with `-lrpc=trace`. If the machine is receiving a lot of traffic the logs will be VERY verbose so it would make sense to reduce the incoming traffic to the bare minimum before turning on logging.

**Comment by androzd** [comment]
[logs.txt](https://github.com/paritytech/parity-ethereum/files/4129246/logs.txt)

This log file
Last received block is 9378197

**Comment by androzd** [comment]
After 25 minutes I got this log:

2020-01-29 18:08:15  IO Worker #0 INFO import  Syncing #9378289 0xefbd…ae7d    33.33 blk/s 5100.0 tx/s  333.1 Mgas/s      0+   15 Qed  #9378309    0/100 peers   257 MiB chain 87 MiB db 1 MiB queue 13 MiB sync  RPC:  0 conn,    5 req/s, 1579 µs
2020-01-29 18:08:15  IO Worker #2 INFO import  Syncing #9378289 0xefbd…ae7d     0.01 blk/s    1.7 tx/s    0.1 Mgas/s      0+   15 Qed  #9378309    0/100 peers   257 MiB chain 87 MiB db 1 MiB queue 13 MiB sync  RPC:  0 conn,    5 req/s, 1579 µs
2020-01-29 18:08:15  IO Worker #1 INFO import  Syncing #9378289 0xefbd…ae7d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   15 Qed  #9378309    0/100 peers   257 MiB chain 87 MiB db 1 MiB queue 13 MiB sync  RPC:  0 conn,    5 req/s, 1579 µs
2020-01-29 18:08:15  IO Worker #0 INFO import  Syncing #9378289 0xefbd…ae7d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   15 Qed  #9378309    0/100 peers   257 MiB chain 87 MiB db 1 MiB queue 13 MiB sync  RPC:  0 conn,    5 req/s, 1579 µs
2020-01-29 18:08:15  IO Worker #2 INFO import  Syncing #9378289 0xefbd…ae7d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   15 Qed  #9378309    0/100 peers   257 MiB chain 87 MiB db 1 MiB queue 13 MiB sync  RPC:  0 conn,    5 req/s, 1579 µs
2020-01-29 18:08:15  IO Worker #1 INFO import  Syncing #9378289 0xefbd…ae7d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   15 Qed  #9378309    0/100 peers   257 MiB chain 87 MiB db 1 MiB queue 13 MiB sync  RPC:  0 conn,    5 req/s, 1579 µs
2020-01-29 18:08:15  IO Worker #0 INFO import  Syncing #9378289 0xefbd…ae7d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   15 Qed  #9378309    0/100 peers   257 MiB chain 87 MiB db 1 MiB queue 13 MiB sync  RPC:  0 conn,    5 req/s, 1579 µs
2020-01-29 18:08:15  IO Worker #2 INFO import  Syncing #9378289 0xefbd…ae7d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   15 Qed  #9378309    0/100 peers   257 MiB chain 87 MiB db 1 MiB queue 13 MiB sync  RPC:  0 conn,    5 req/s, 1579 µs
2020-01-29 18:08:15  IO Worker #1 INFO import  Syncing #9378289 0xefbd…ae7d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   15 Qed  #9378309    0/100 peers   257 MiB chain 87 MiB db 1 MiB queue 13 MiB sync  RPC:  0 conn,    5 req/s, 1579 µs
2020-01-29 18:08:15  IO Worker #0 INFO import  Syncing #9378289 0xefbd…ae7d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   15 Qed  #9378309    0/100 peers   257 MiB chain 87 MiB db 1 MiB queue 13 MiB sync  RPC:  0 conn,    5 req/s, 1579 µs
2020-01-29 18:08:15  IO Worker #2 INFO import  Syncing #9378289 0xefbd…ae7d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   15 Qed  #9378309    0/100 peers   257 MiB chain 87 MiB db 1 MiB queue 13 MiB sync  RPC:  0 conn,    5 req/s, 1579 µs
2020-01-29 18:08:15  IO Worker #1 INFO import  Syncing #9378289 0xefbd…ae7d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   15 Qed  #9378309    0/100 peers   257 MiB chain 87 MiB db 1 MiB queue 13 MiB sync  RPC:  0 conn,    5 req/s, 1579 µs
2020-01-29 18:08:15  IO Worker #0 INFO import  Syncing #9378289 0xefbd…ae7d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   15 Qed  #9378309    0/100 peers   257 MiB chain 87 MiB db 1 MiB queue 13 MiB sync  RPC:  0 conn,    5 req/s, 1579 µs
2020-01-29 18:08:15  IO Worker #2 INFO import  Syncing #9378289 0xefbd…ae7d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   15 Qed  #9378309    0/100 peers   257 MiB chain 87 MiB db 1 MiB queue 13 MiB sync  RPC:  0 conn,    5 req/s, 1579 µs
2020-01-29 18:08:45  IO Worker #1 INFO import  Syncing #9378289 0xefbd…ae7d     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   15 Qed  #9378309    0/100 peers   257 MiB chain 87 MiB db 1 MiB queue 13 MiB sync  RPC:  0 conn,    0 req/s, 1579 µs

**Comment by niklasad1** [comment]
@androzd Would be useful to know which `rpc request` was the last before panicking, can you provide that? 

For example at  `16:39` would be interesting to see the log then.

**Comment by androzd** [comment]
I can't restore this information. 

After 4-5 restarts problem is changed, and now I got a syncing freezes. Syncing delay for 3-5 minutes

Most frequent requests is:
eth_getBalance
eth_blockNumber
eth_getBlockByNumber
eth_getTransactionByHash
eth_getTransactionReceipt

and not frequent is: personal_newAccount.

When freeze starts 100% ram is used (128 GB)

**Comment by androzd** [comment]
With disabled RPC works fine. But I need RPC too much

**Comment by androzd** [comment]
More info

10 minutes without RPC works fine
Later no new blocks synced

**Comment by baginail** [comment]
I have the same

**Comment by baginail** [comment]
янв 29 21:25:43 ubuntu parity[850]: 2020-01-29 21:25:43  Syncing #9378392 0x6b7e…5996     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   23 Qed  #9378416   35/50 peers     74 KiB chain   74 MiB db    2 Mi
янв 29 21:25:43 ubuntu parity[850]: 2020-01-29 21:25:43  Syncing #9378392 0x6b7e…5996     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   23 Qed  #9378416   35/50 peers     74 KiB chain   74 MiB db    2 Mi
янв 29 21:25:43 ubuntu parity[850]: 2020-01-29 21:25:43  Syncing #9378392 0x6b7e…5996     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   23 Qed  #9378416   35/50 peers     74 KiB chain   74 MiB db    2 Mi
янв 29 21:25:43 ubuntu parity[850]: 2020-01-29 21:25:43  Syncing #9378392 0x6b7e…5996     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   23 Qed  #9378416   35/50 peers     74 KiB chain   74 MiB db    2 Mi
янв 29 21:25:43 ubuntu parity[850]: 2020-01-29 21:25:43  Syncing #9378392 0x6b7e…5996     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   23 Qed  #9378416   35/50 peers     74 KiB chain   74 MiB db    2 Mi
янв 29 21:25:43 ubuntu parity[850]: 2020-01-29 21:25:43  Syncing #9378392 0x6b7e…5996     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   23 Qed  #9378416   35/50 peers     74 KiB chain   74 MiB db    2 Mi
янв 29 21:25:43 ubuntu parity[850]: 2020-01-29 21:25:43  Syncing #9378392 0x6b7e…5996     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   23 Qed  #9378416   35/50 peers     74 KiB chain   74 MiB db    2 Mi
янв 29 21:25:43 ubuntu parity[850]: 2020-01-29 21:25:43  Syncing #9378392 0x6b7e…5996     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   23 Qed  #9378416   35/50 peers     74 KiB chain   74 MiB db    2 Mi
янв 29 21:25:43 ubuntu parity[850]: 2020-01-29 21:25:43  Syncing #9378392 0x6b7e…5996     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   23 Qed  #9378416   35/50 peers     74 KiB chain   74 MiB db    2 Mi
янв 29 21:25:43 ubuntu parity[850]: 2020-01-29 21:25:43  Syncing #9378392 0x6b7e…5996     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   23 Qed  #9378416   35/50 peers     74 KiB chain   74 MiB db    2 Mi

**Comment by dvdplm** [comment]
I think we're looking at two separate issues: syncing stalling is likely unrelated to the RPC panic. Let's keep this ticket focused on the panic. 
We might need to make some kind of custom build to figure that out. What flavour of Linux are you running?

Also, to get to the bottom of this we'll need to figure out which RPC is causing the panic. @androzd can you please run RPC calls, one at a time and with logging turned on until we find which one is causing this? Thanks.

**Comment by dvdplm** [comment]
> I have the same

@baginail Please open a separate ticket if your issue concerns peer count or syncing problems. Let's keep this issue focused on the RPC panic that @androzd is experiencing. Thanks.

**Comment by androzd** [comment]
Issue with RPC panic is selfsolved.. I don't know how it solved. And I can't reproduce it.

Only issue with syncing now reproduced

**Comment by baginail** [comment]
> I think we're looking at two separate issues: syncing stalling is likely unrelated to the RPC panic. Let's keep this ticket focused on the panic.
> We might need to make some kind of custom build to figure that out. What flavour of Linux are you running?
> 
> Also, to get to the bottom of this we'll need to figure out which RPC is causing the panic. @androzd can you please run RPC calls, one at a time and with logging turned on until we find which one is causing this? Thanks.

i have open ethereum pool, uses rpc

**Comment by dvdplm** [comment]
> Issue with RPC panic is selfsolved.. I don't know how it solved. And I can't reproduce it.
> 
> Only issue with syncing now reproduced

Ok, in that case I'm going to close this issue now. Feel free to open a new one if you can reproduce the panic again.
