### ISSUE TITLE
Thread 'http.worker10' panicked at 'decode db value failed: RlpExpectedToBeList', src/libcore/result.rs:1165

### ISSUE THREAD

**Issue by igorbarinov** [paritytech/parity-ethereum#11424]
After upgrade to 2.7.0 from 2.6.8 on Archive node I see this message in logs 

```
parity         | 2020-01-30 09:14:10 UTC Panic occurred, see stderr for details
parity         | 
parity         | 
parity         | ====================
parity         | 
parity         | stack backtrace:
parity         |    0:     0x55ee17e042ed - <no info>
parity         |    1:     0x55ee1860a558 - <no info>
parity         |    2:     0x55ee1889090a - <no info>
parity         |    3:     0x55ee190cba53 - <no info>
parity         |    4:     0x55ee190cb7dd - <no info>
parity         |    5:     0x55ee190e6f55 - <no info>
parity         |    6:     0x55ee17ebcd3c - <no info>
parity         |    7:     0x55ee17ec30f5 - <no info>
parity         |    8:     0x55ee18037baa - <no info>
parity         |    9:     0x55ee18078de9 - <no info>
parity         |   10:     0x55ee186cc53c - <no info>
parity         |   11:     0x55ee189558d5 - <no info>
parity         |   12:     0x55ee1868f874 - <no info>
parity         |   13:     0x55ee1887d3b1 - <no info>
parity         |   14:     0x55ee1886a83b - <no info>
parity         |   15:     0x55ee17d68d92 - <no info>
parity         |   16:     0x55ee18966a6f - <no info>
parity         |   17:     0x55ee18968803 - <no info>
parity         |   18:     0x55ee18968803 - <no info>
parity         |   19:     0x55ee18964f92 - <no info>
parity         |   20:     0x55ee18a0483f - <no info>
parity         |   21:     0x55ee18680754 - <no info>
parity         |   22:     0x55ee18698664 - <no info>
parity         |   23:     0x55ee1910fb38 - <no info>
parity         |   24:     0x55ee1910b445 - <no info>
parity         |   25:     0x55ee1910980f - <no info>
parity         |   26:     0x55ee190f59c6 - <no info>
parity         |   27:     0x55ee190ed6ea - <no info>
parity         |   28:     0x55ee191078bd - <no info>
parity         |   29:     0x55ee19108327 - <no info>
parity         |   30:     0x55ee190e5b1e - <no info>
parity         |   31:     0x55ee190e8b4f - <no info>
parity         |   32:     0x7fafb30bc6b9 - <no info>
parity         |   33:     0x7fafb27d041c - <no info>
parity         |   34:                0x0 - <no info>
parity         | 
parity         | Thread 'http.worker10' panicked at 'decode db value failed: RlpExpectedToBeList', src/libcore/result.rs:1165
parity         | 
parity         | This is a bug. Please report it at:
parity         | 
parity         |     https://github.com/paritytech/parity-ethereum/issues/new
```

I'm using the official container with the following settings:

```
    command:
      --chain="$CHAIN"
      --nat="extip:$EXT_IP"
      --tracing=on
      --pruning=archive
      --fat-db=on
      --base-path=/root/data
      --jsonrpc-port=8545
      --jsonrpc-cors=all
      --jsonrpc-interface=all
      --jsonrpc-hosts=all
      --jsonrpc-apis=web3,eth,net,parity,traces
      --ws-interface=all
      --ws-apis=web3,eth,net,parity,pubsub,traces
      --ws-origins=all
      --ws-hosts=all
      --ws-max-connections=2000
      --logging=info
```

restart helped and the node continued to sync after that

The issue is similar to https://github.com/paritytech/parity-ethereum/issues/11421
but #11421 is closed

**Comment by niklasad1** [comment]
Closing duplicated #11422

**Comment by niklasad1** [comment]
@igorbarinov 

BTW, which chain are you using? 

We tried to reproduce this on `goerli` but wasn't successful.  I'm starting to suspect that this is mainnet only but not sure.

**Comment by igorbarinov** [comment]
this error from xDai Archive node

**Comment by dvdplm** [comment]
@igorbarinov Did you also run RPCs on the node at the time of the panic?

**Comment by igorbarinov** [comment]
yes, it's used as an RPC node. it's a node used by blockscout. it many different queries including the reading of traces

**Comment by dvdplm** [comment]
It would be super useful to get the RPC logs from the time of the panic so we can figure out the which RPC method was called and block/transaction hashes involved. Do you think you can run the node with `-lrpc=trace` until it crashes? Thanks!

**Comment by igorbarinov** [comment]
ok I turned trace logging https://seashells.io/v/gRRHBJTR
and got some results 
```
arity         | 2020-01-30 10:58:44 UTC http.worker30 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7c0629","id":2085825}.
parity         | 2020-01-30 10:58:44 UTC http.worker10 TRACE rpc  Request: {"jsonrpc":"2.0","id":2085826,"method":"eth_blockNumber","params":[]}.
parity         | 2020-01-30 10:58:44 UTC http.worker10 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7c0629","id":2085826}.
parity         | 2020-01-30 10:58:44 UTC http.worker30 TRACE rpc  Request: {"jsonrpc":"2.0","id":2085827,"method":"eth_blockNumber","params":[]}.
parity         | 2020-01-30 10:58:44 UTC http.worker30 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7c0629","id":2085827}.
parity         | 2020-01-30 10:58:44 UTC http.worker10 TRACE rpc  Request: {"jsonrpc":"2.0","id":2085828,"method":"eth_blockNumber","params":[]}.
parity         | 2020-01-30 10:58:44 UTC http.worker10 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7c0629","id":2085828}.
parity         | 2020-01-30 10:58:44 UTC http.worker20 TRACE rpc  Request: {"jsonrpc":"2.0","id":2085829,"method":"eth_blockNumber","params":[]}.
parity         | 2020-01-30 10:58:44 UTC http.worker20 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7c0629","id":2085829}.
parity         | 2020-01-30 10:58:44 UTC http.worker20 TRACE rpc  Request: {"jsonrpc": "2.0", "method": "eth_blockNumber", "params": [], "id": 348827}.
parity         | 2020-01-30 10:58:44 UTC http.worker20 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7c0629","id":348827}.
parity         | 2020-01-30 10:58:44 UTC http.worker30 TRACE rpc  Request: {"jsonrpc":"2.0","id":2085830,"method":"eth_blockNumber","params":[]}.
parity         | 2020-01-30 10:58:44 UTC http.worker30 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7c0629","id":2085830}.
parity         | 2020-01-30 10:58:44 UTC http.worker10 TRACE rpc  Request: {"jsonrpc":"2.0","id":2085831,"method":"eth_blockNumber","params":[]}.
parity         | 2020-01-30 10:58:44 UTC http.worker10 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7c0629","id":2085831}.
parity         | 2020-01-30 10:58:45 UTC http.worker20 TRACE rpc  Request: {"jsonrpc":"2.0","id":2085832,"method":"eth_blockNumber","params":[]}.
parity         | 2020-01-30 10:58:45 UTC http.worker20 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7c0629","id":2085832}.
parity         | 2020-01-30 10:58:45 UTC http.worker20 TRACE rpc  Request: [{"id":0,"jsonrpc":"2.0","method":"trace_block","params":["0x7BDE1A"]},{"id":1,"jsonrpc":"2.0","method":"trace_block","params":["0x7BDE33"]},{"id":2,"jsonrpc":"2.0","method":"trace_block","params":["0x7BF335"]},{"id":3,"jsonrpc":"2.0","method":"trace_block","params":["0x7BF38F"]},{"id":4,"jsonrpc":"2.0","method":"trace_block","params":["0x7BF3B0"]},{"id":5,"jsonrpc":"2.0","method":"trace_block","params":["0x7BF3B4"]},{"id":6,"jsonrpc":"2.0","method":"trace_block","params":["0x7BF401"]},{"id":7,"jsonrpc":"2.0","method":"trace_block","params":["0x7BF44B"]},{"id":8,"jsonrpc":"2.0","method":"trace_block","params":["0x7C04F0"]},{"id":9,"jsonrpc":"2.0","method":"trace_block","params":["0x7C04F4"]}].
parity         | 2020-01-30 10:58:45 UTC http.worker30 TRACE rpc  Request: {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest",true],"id":88855}.
parity         | 2020-01-30 10:58:45 UTC http.worker30 DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"author":"0x9e41ba620feba8198369c26351063b26ec5b7c9e","difficulty":"0xfffffffffffffffffffffffffffffffe","extraData":"0xde830206088f5061726974792d457468657265756d86312e34302e30826c69","gasLimit":"0x989680","gasUsed":"0x0","hash":"0xba92a8c942d5c004192ae8b82c30c569f68c5365e281e60efb7d1ed9f2c87737","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x9e41ba620feba8198369c26351063b26ec5b7c9e","number":"0x7c0629","parentHash":"0x09055ebebb70974391ef39598f8301fe71a711ac4056e622b5f550b739a5db34","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sealFields":["0x8412d6f160","0xb841721aa76eacad750944da51b866e705060b0fef4142e987f3e6bbb7bfd4994b8a3b2851fda38229d5abf9bb17c6949613b3d14b3755db78e5f9c305aba98700b800"],"sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","signature":"721aa76eacad750944da51b866e705060b0fef4142e987f3e6bbb7bfd4994b8a3b2851fda38229d5abf9bb17c6949613b3d14b3755db78e5f9c305aba98700b800","size":"0x24c","stateRoot":"0x95e8c784f18d524c165875e1f68d7c6aa7b5bfd30c30662a13328fb84b3f25e5","step":"316076384","timestamp":"0x5e32b6e0","totalDifficulty":"0x7c0628ffffffffffffffffffffffffecaf0877","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]},"id":88855}.
parity         | 2020-01-30 10:58:45 UTC http.worker30 TRACE rpc  Request: {"jsonrpc":"2.0","id":2085833,"method":"eth_blockNumber","params":[]}.
parity         | 2020-01-30 10:58:45 UTC http.worker30 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7c0629","id":2085833}.
parity         | 2020-01-30 10:58:45 UTC http.worker20 WARN parity  Panic occurred, see stderr for details
parity         |
parity         |
parity         | ====================
parity         |
parity         | stack backtrace:
parity         |    0:     0x55b70cf682ed - <no info>
parity         |    1:     0x55b70d76e558 - <no info>
parity         |    2:     0x55b70d9f490a - <no info>
parity         |    3:     0x55b70e22fa53 - <no info>
parity         |    4:     0x55b70e22f7dd - <no info>
parity         |    5:     0x55b70e24af55 - <no info>
parity         |    6:     0x55b70d020d3c - <no info>
parity         |    7:     0x55b70d0270f5 - <no info>
parity         |    8:     0x55b70d19bbaa - <no info>
parity         |    9:     0x55b70d1dcde9 - <no info>
parity         |   10:     0x55b70d83053c - <no info>
parity         |   11:     0x55b70dab98d5 - <no info>
parity         |   12:     0x55b70d7f3874 - <no info>
parity         |   13:     0x55b70d9e13b1 - <no info>
parity         |   14:     0x55b70d9ce83b - <no info>
parity         |   15:     0x55b70ceccd92 - <no info>
parity         |   16:     0x55b70dacaa6f - <no info>
parity         |   17:     0x55b70dacc803 - <no info>
parity         |   18:     0x55b70dacc803 - <no info>
parity         |   19:     0x55b70dac8f92 - <no info>
parity         |   20:     0x55b70db6883f - <no info>
parity         |   21:     0x55b70d7e4754 - <no info>
parity         |   22:     0x55b70d7fc664 - <no info>
parity         |   23:     0x55b70e273b38 - <no info>
parity         |   24:     0x55b70e26f445 - <no info>
parity         |   25:     0x55b70e26d80f - <no info>
parity         |   26:     0x55b70e2599c6 - <no info>
parity         |   27:     0x55b70e2516ea - <no info>
parity         |   28:     0x55b70e26b8bd - <no info>
parity         |   29:     0x55b70e26c327 - <no info>
parity         |   30:     0x55b70e249b1e - <no info>
parity         |   31:     0x55b70e24cb4f - <no info>
parity         |   32:     0x7f7dafd8a6b9 - <no info>
parity         |   33:     0x7f7daf49e41c - <no info>
parity         |   34:                0x0 - <no info>
parity         |
parity         | Thread 'http.worker20' panicked at 'decode db value failed: RlpExpectedToBeList', src/libcore/result.rs:1165
parity         |
parity         | This is a bug. Please report it at:
parity         |
parity         |     https://github.com/paritytech/parity-ethereum/issues/new
parity         |
parity         |
parity         | 2020-01-30 10:58:45 UTC http.worker10 TRACE rpc  Request: {"jsonrpc":"2.0","id":2085834,"method":"eth_blockNumber","params":[]}.
parity         | 2020-01-30 10:58:45 UTC http.worker10 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7c0629","id":2085834}.
parity         | 2020-01-30 10:58:45 UTC main INFO parity_ethereum::run  Finishing work, please wait...
parity         | 2020-01-30 10:58:45 UTC http.worker20 TRACE rpc  Request: {"jsonrpc": "2.0", "method": "net_version", "params": [], "id": 348828}.
parity         | 2020-01-30 10:58:45 UTC http.worker20 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"100","id":348828}.
letsencrypt    | 2020/01/30 10:58:46 Received event die for container 3e856efb46e2
dockergen      | 2020/01/30 10:58:46 Received event die for container 3e856efb46e2
parity exited with code 1
ethstats       | /usr/src/app/node_modules/web3/lib/web3/httpprovider.js:87
ethstats       |         throw errors.InvalidResponse(request.responseText);
ethstats       |         ^
ethstats       |
ethstats       | Error: Invalid JSON RPC response: undefined
ethstats       |     at Object.InvalidResponse (/usr/src/app/node_modules/web3/lib/web3/errors.js:35:16)
ethstats       |     at HttpProvider.send (/usr/src/app/node_modules/web3/lib/web3/httpprovider.js:87:22)
ethstats       |     at RequestManager.send (/usr/src/app/node_modules/web3/lib/web3/requestmanager.js:58:32)
ethstats       |     at Eth.get [as mining] (/usr/src/app/node_modules/web3/lib/web3/property.js:107:62)
ethstats       |     at hashrate (/usr/src/app/lib/node.js:494:18)
ethstats       |     at /usr/src/app/node_modules/async/lib/async.js:718:13
ethstats       |     at async.forEachOf.async.eachOf (/usr/src/app/node_modules/async/lib/async.js:233:13)
ethstats       |     at _parallel (/usr/src/app/node_modules/async/lib/async.js:717:9)
ethstats       |     at Object.async.parallel (/usr/src/app/node_modules/async/lib/async.js:731:9)
ethstats       |     at Node.getStats (/usr/src/app/lib/node.js:483:9)
ethstats       | npm ERR! code ELIFECYCLE
ethstats       | npm ERR! errno 1
ethstats       | npm ERR! eth-net-intelligence-api@0.1.1 start: `node ./app.js`
ethstats       | npm ERR! Exit status 1
ethstats       | npm ERR!
ethstats       | npm ERR! Failed at the eth-net-intelligence-api@0.1.1 start script.
ethstats       | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
ethstats       |
ethstats       | npm ERR! A complete log of this run can be found in:
ethstats       | npm ERR!     /root/.npm/_logs/2020-01-30T10_58_47_728Z-debug.log
dockergen      | 2020/01/30 10:58:47 Received event die for container e08f21eec356
letsencrypt    | 2020/01/30 10:58:47 Received event die for container e08f21eec356
letsencrypt    | 2020/01/30 10:58:47 Received event start for container 3e856efb46e2
dockergen      | 2020/01/30 10:58:47 Received event start for container 3e856efb46e2
dockergen      | 2020/01/30 10:58:48 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
ethstats exited with code 1
letsencrypt    | 2020/01/30 10:58:49 Received event start for container e08f21eec356
dockergen      | 2020/01/30 10:58:49 Received event start for container e08f21eec356
parity         | 2020-01-30 10:58:49 UTC http.worker30 TRACE rpc  Request: {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest",true],"id":88867}.
parity         | 2020-01-30 10:58:49 UTC http.worker10 TRACE rpc  Request: {"jsonrpc":"2.0","id":2086028,"method":"eth_blockNumber","params":[]}.
parity         | 2020-01-30 10:58:49 UTC http.worker10 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7c0629","id":2086028}.
parity         | 2020-01-30 10:58:49 UTC http.worker30 DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"author":"0x9e41ba620feba8198369c26351063b26ec5b7c9e","difficulty":"0xfffffffffffffffffffffffffffffffe","extraData":"0xde830206088f5061726974792d457468657265756d86312e34302e30826c69","gasLimit":"0x989680","gasUsed":"0x0","hash":"0xba92a8c942d5c004192ae8b82c30c569f68c5365e281e60efb7d1ed9f2c87737","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x9e41ba620feba8198369c26351063b26ec5b7c9e","number":"0x7c0629","parentHash":"0x09055ebebb70974391ef39598f8301fe71a711ac4056e622b5f550b739a5db34","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sealFields":["0x8412d6f160","0xb841721aa76eacad750944da51b866e705060b0fef4142e987f3e6bbb7bfd4994b8a3b2851fda38229d5abf9bb17c6949613b3d14b3755db78e5f9c305aba98700b800"],"sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","signature":"721aa76eacad750944da51b866e705060b0fef4142e987f3e6bbb7bfd4994b8a3b2851fda38229d5abf9bb17c6949613b3d14b3755db78e5f9c305aba98700b800","size":"0x24c","stateRoot":"0x95e8c784f18d524c165875e1f68d7c6aa7b5bfd30c30662a13328fb84b3f25e5","step":"316076384","timestamp":"0x5e32b6e0","totalDifficulty":"0x7c0628ffffffffffffffffffffffffecaf0877","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]},"id":88867}.
parity         | 2020-01-30 10:58:49 UTC http.worker10 TRACE rpc  Request: [{"id":0,"jsonrpc":"2.0","method":"trace_block","params":["0x7BDE1D"]},{"id":1,"jsonrpc":"2.0","method":"trace_block","params":["0x7BDE43"]},{"id":2,"jsonrpc":"2.0","method":"trace_block","params":["0x7BDE5D"]},{"id":3,"jsonrpc":"2.0","method":"trace_block","params":["0x7BF30B"]},{"id":4,"jsonrpc":"2.0","method":"trace_block","params":["0x7BF34E"]},{"id":5,"jsonrpc":"2.0","method":"trace_block","params":["0x7BF400"]},{"id":6,"jsonrpc":"2.0","method":"trace_block","params":["0x7BF442"]},{"id":7,"jsonrpc":"2.0","method":"trace_block","params":["0x7BF47D"]},{"id":8,"jsonrpc":"2.0","method":"trace_block","params":["0x7BF48E"]},{"id":9,"jsonrpc":"2.0","method":"trace_block","params":["0x7C04D2"]}].
dockergen      | 2020/01/30 10:58:49 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
parity         | 2020-01-30 10:58:49 UTC http.worker10 WARN parity  Panic occurred, see stderr for details
parity         |
parity         |
parity         | ====================
parity         |
parity         | stack backtrace:
parity         |    0:     0x55f547bd02ed - <no info>
parity         |    1:     0x55f5483d6558 - <no info>
parity         |    2:     0x55f54865c90a - <no info>
parity         |    3:     0x55f548e97a53 - <no info>
parity         |    4:     0x55f548e977dd - <no info>
parity         |    5:     0x55f548eb2f55 - <no info>
parity         |    6:     0x55f547c88d3c - <no info>
parity         |    7:     0x55f547c8f0f5 - <no info>
parity         |    8:     0x55f547e03baa - <no info>
parity         |    9:     0x55f547e44de9 - <no info>
parity         |   10:     0x55f54849853c - <no info>
parity         |   11:     0x55f5487218d5 - <no info>
parity         |   12:     0x55f54845b874 - <no info>
parity         |   13:     0x55f5486493b1 - <no info>
parity         |   14:     0x55f54863683b - <no info>
parity         |   15:     0x55f547b34d92 - <no info>
parity         |   16:     0x55f548732a6f - <no info>
parity         |   17:     0x55f548734803 - <no info>
parity         |   18:     0x55f548734803 - <no info>
parity         |   19:     0x55f548730f92 - <no info>
parity         |   20:     0x55f5487d083f - <no info>
parity         |   21:     0x55f54844c754 - <no info>
parity         |   22:     0x55f548464664 - <no info>
parity         |   23:     0x55f548edbb38 - <no info>
parity         |   24:     0x55f548ed7445 - <no info>
parity         |   25:     0x55f548ed580f - <no info>
parity         |   26:     0x55f548ec19c6 - <no info>
parity         |   27:     0x55f548eb96ea - <no info>
parity         |   28:     0x55f548ed38bd - <no info>
parity         |   29:     0x55f548ed4327 - <no info>
parity         |   30:     0x55f548eb1b1e - <no info>
parity         |   31:     0x55f548eb4b4f - <no info>
parity         |   32:     0x7fa523afd6b9 - <no info>
parity         |   33:     0x7fa52321141c - <no info>
parity         |   34:                0x0 - <no info>
parity         |
parity         | Thread 'http.worker10' panicked at 'decode db value failed: RlpExpectedToBeList', src/libcore/result.rs:1165
parity         |
parity         | This is a bug. Please report it at:
parity         |
parity         |     https://github.com/paritytech/parity-ethereum/issues/new
parity         |
parity         |
parity         | 2020-01-30 10:58:49 UTC http.worker10 TRACE rpc  Request: {"jsonrpc":"2.0","id":2086029,"method":"eth_blockNumber","params":[]}.
parity         | 2020-01-30 10:58:49 UTC http.worker10 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7c0629","id":2086029}.
parity         | 2020-01-30 10:58:49 UTC main INFO parity_ethereum::run  Finishing work, please wait...
parity         | 2020-01-30 10:58:49 UTC http.worker10 TRACE rpc  Request: {"jsonrpc":"2.0","id":2086030,"method":"eth_blockNumber","params":[]}.
parity         | 2020-01-30 10:58:49 UTC http.worker10 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7c0629","id":2086030}.
parity         | 2020-01-30 10:58:49 UTC http.worker20 TRACE rpc  Request: {"id":1,"jsonrpc":"2.0","method":"eth_blockNumber","params":[]}.
parity         | 2020-01-30 10:58:49 UTC http.worker20 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7c0629","id":1}.
dockergen      | 2020/01/30 10:58:49 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
parity         | 2020-01-30 10:58:49 UTC http.worker30 TRACE rpc  Request: {"jsonrpc":"2.0","id":2086031,"method":"eth_blockNumber","params":[]}.
parity         | 2020-01-30 10:58:49 UTC http.worker30 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7c0629","id":2086031}.
parity         | 2020-01-30 10:58:49 UTC http.worker00 TRACE rpc  Request: {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest",true],"id":88868}.
parity         | 2020-01-30 10:58:49 UTC http.worker00 DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"author":"0x9e41ba620feba8198369c26351063b26ec5b7c9e","difficulty":"0xfffffffffffffffffffffffffffffffe","extraData":"0xde830206088f5061726974792d457468657265756d86312e34302e30826c69","gasLimit":"0x989680","gasUsed":"0x0","hash":"0xba92a8c942d5c004192ae8b82c30c569f68c5365e281e60efb7d1ed9f2c87737","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x9e41ba620feba8198369c26351063b26ec5b7c9e","number":"0x7c0629","parentHash":"0x09055ebebb70974391ef39598f8301fe71a711ac4056e622b5f550b739a5db34","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sealFields":["0x8412d6f160","0xb841721aa76eacad750944da51b866e705060b0fef4142e987f3e6bbb7bfd4994b8a3b2851fda38229d5abf9bb17c6949613b3d14b3755db78e5f9c305aba98700b800"],"sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","signature":"721aa76eacad750944da51b866e705060b0fef4142e987f3e6bbb7bfd4994b8a3b2851fda38229d5abf9bb17c6949613b3d14b3755db78e5f9c305aba98700b800","size":"0x24c","stateRoot":"0x95e8c784f18d524c165875e1f68d7c6aa7b5bfd30c30662a13328fb84b3f25e5","step":"316076384","timestamp":"0x5e32b6e0","totalDifficulty":"0x7c0628ffffffffffffffffffffffffecaf0877","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]},"id":88868}.
parity         | 2020-01-30 10:58:49 UTC http.worker10 TRACE rpc  Request: {"jsonrpc":"2.0","id":2086032,"method":"eth_blockNumber","params":[]}.
parity         | 2020-01-30 10:58:49 UTC http.worker10 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x7c0629","id":2086032}.
dockergen      | 2020/01/30 10:58:49 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
parity         | 2020-01-30 10:58:49 UTC Verifier #1 WARN engine  Not preparing block; cannot sign.
parity         | 2020-01-30 10:58:49 UTC Verifier #1 WARN engine  Not preparing block; cannot sign.
ethstats       |
ethstats       | > eth-net-intelligence-api@0.1.1 start /usr/src/app
ethstats       | > node ./app.js
ethstats       |
letsencrypt    | 2020/01/30 10:58:50 Received event die for container 3e856efb46e2
dockergen      | 2020/01/30 10:58:50 Received event die for container 3e856efb46e2
ethstats       | [eth] =✘= Web3 connection attempt #0 failed
ethstats       | [eth] =✘= Trying again in 500 ms
parity exited with code 1
ethstats       | [eth] =✘= Web3 connection attempt #1 failed
ethstats       | [eth] =✘= Trying again in 1000 ms
dockergen      | 2020/01/30 10:58:52 Received event start for container 3e856efb46e2
letsencrypt    | 2020/01/30 10:58:52 Received event start for container 3e856efb46e2
parity         | 2020-01-30 10:58:52 UTC main INFO parity_ethereum::run  Starting Parity-Ethereum/v2.7.0-stable-748eda2-20200127/x86_64-unknown-linux-gnu/rustc1.40.0
parity         | 2020-01-30 10:58:52 UTC main INFO parity_ethereum::run  Keys path /root/data/keys/xdai
parity         | 2020-01-30 10:58:52 UTC main INFO parity_ethereum::run  DB path /root/data/chains/xdai/db/3c648cbdc4c9333d
parity         | 2020-01-30 10:58:52 UTC main INFO parity_ethereum::run  State DB configuration: archive +Fat +Trace
parity         | 2020-01-30 10:58:52 UTC main INFO parity_ethereum::run  Operating mode: active
parity         | 2020-01-30 10:58:52 UTC main WARN parity_ethereum::run  Warning: Warp Sync is disabled because Fat DB is turned on.
parity         | 2020-01-30 10:58:52 UTC main WARN engine  Not preparing block; cannot sign.
dockergen      | 2020/01/30 10:58:52 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
dockergen      | 2020/01/30 10:58:52 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
```
