### ISSUE TITLE
parity-1.11.x build failure for nix

### ISSUE THREAD

**Issue by akru** [paritytech/parity-ethereum#8612]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.11.0
> - **Which operating system?**: Linux
> - **How installed?**: from source

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

```
...
<3>TARGET = Some("x86_64-unknown-linux-gnu")
<3>HOST = Some("x86_64-unknown-linux-gnu")
<3>TARGET = Some("x86_64-unknown-linux-gnu")
<3>TARGET = Some("x86_64-unknown-linux-gnu")
<3>HOST = Some("x86_64-unknown-linux-gnu")
<3>CC_x86_64-unknown-linux-gnu = None
<3>CC_x86_64_unknown_linux_gnu = None
<3>HOST_CC = None
<3>CC = Some("gcc")
<3>TARGET = Some("x86_64-unknown-linux-gnu")
<3>HOST = Some("x86_64-unknown-linux-gnu")
<3>CFLAGS_x86_64-unknown-linux-gnu = None
<3>CFLAGS_x86_64_unknown_linux_gnu = None
<3>HOST_CFLAGS = None
<3>CFLAGS = None
<3>DEBUG = Some("false")
<3>running "gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wmissing-prototypes" "-Wnested-externs" "-Wstrict-prototypes" "-fdata-sections" "-ffunction-sections" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-declarations" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-Wno-cast-align" "-fstack-protector" "-g3" "-DNDEBUG" "-D_XOPEN_SOURCE=700" "-c" "-o/tmp/nix-build-parity-1.11.0.drv-0/source/target/release/build/ring-0b4f2e52658f805b/out/ecp_nistz.o" "crypto/ec/ecp_nistz.c"
<3>
<3>--- stderr
<3>thread '<unnamed>' panicked at '"/tmp/nix-build-parity-1.11.0.drv-0/parity-1.11.0-vendor/ring/pregenerated/aes-x86_64-elf.S": Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
<3>note: Run with `RUST_BACKTRACE=1` for a backtrace.
<3>thread '<unnamed>' panicked at '"/tmp/nix-build-parity-1.11.0.drv-0/parity-1.11.0-vendor/ring/pregenerated/aesni-x86_64-elf.S": Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
<3>thread '<unnamed>' panicked at '"/tmp/nix-build-parity-1.11.0.drv-0/parity-1.11.0-vendor/ring/pregenerated/bsaes-x86_64-elf.S": Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
<3>thread '<unnamed>' panicked at '"/tmp/nix-build-parity-1.11.0.drv-0/parity-1.11.0-vendor/ring/pregenerated/vpaes-x86_64-elf.S": Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
<3>thread '<unnamed>' panicked at '"/tmp/nix-build-parity-1.11.0.drv-0/parity-1.11.0-vendor/ring/pregenerated/x86_64-mont-elf.S": Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
<3>thread '<unnamed>' panicked at '"/tmp/nix-build-parity-1.11.0.drv-0/parity-1.11.0-vendor/ring/pregenerated/x86_64-mont5-elf.S": Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
<3>thread '<unnamed>' panicked at '"/tmp/nix-build-parity-1.11.0.drv-0/parity-1.11.0-vendor/ring/pregenerated/chacha-x86_64-elf.S": Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
<3>thread '<unnamed>' panicked at '"/tmp/nix-build-parity-1.11.0.drv-0/parity-1.11.0-vendor/ring/pregenerated/ecp_nistz256-x86_64-elf.S": Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
<3>thread '<unnamed>' panicked at '"/tmp/nix-build-parity-1.11.0.drv-0/parity-1.11.0-vendor/ring/pregenerated/p256-x86_64-asm-elf.S": Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
<3>thread '<unnamed>' panicked at '"/tmp/nix-build-parity-1.11.0.drv-0/parity-1.11.0-vendor/ring/pregenerated/aesni-gcm-x86_64-elf.S": Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
<3>thread '<unnamed>' panicked at '"/tmp/nix-build-parity-1.11.0.drv-0/parity-1.11.0-vendor/ring/pregenerated/ghash-x86_64-elf.S": Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
<3>thread '<unnamed>' panicked at '"/tmp/nix-build-parity-1.11.0.drv-0/parity-1.11.0-vendor/ring/pregenerated/poly1305-x86_64-elf.S": Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
<3>thread '<unnamed>' panicked at '"/tmp/nix-build-parity-1.11.0.drv-0/parity-1.11.0-vendor/ring/pregenerated/sha512-x86_64-elf.S": Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
<3>thread '<unnamed>' panicked at '"/tmp/nix-build-parity-1.11.0.drv-0/parity-1.11.0-vendor/ring/pregenerated/sha256-x86_64-elf.S": Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
<3>
<3>warning: build failed, waiting for other jobs to finish...
<3>error: build failed
```

[full log](https://hydra.aira.life/build/1788/nixlog/2)

So, it's not supported by paritytech use case, but building with Nix is important for us.
May be someone from programmers or devops can explain the reason of failure?

@General-Beck what do you think about it?

**Comment by sorpaas** [comment]
Looks like update of ring broke NixOS build. Might also consider opening this issue on ring's repo or nixpkgs' repo.

In particular, I think if we can trick ring's build script to not use pregenerated asm, this issue can be fixed. https://github.com/briansmith/ring/blob/master/build.rs#L399

**Comment by akru** [comment]
Okay, I have success build with patched `ring`.

**Comment by briansmith** [comment]
I recommend trying to get back onto a release version of *ring* so that you don't need workarounds like this. Changes in the pipeline for *ring* will make it more difficult to maintain a fork of *ring*, and also building from a git checkout instead of from crates.io will become more complicated and will likely require some special tooling.

**Comment by akru** [comment]
Sounds good, @briansmith, can I hope for your help to build mainstream ring via cargo-vendor tool? Currently I have a problem on top of this issue.

**Comment by briansmith** [comment]
In general I think supporting cargo-vendor sounds like a good idea. I don't know what's required; maybe we just need to add a check in build.rs to see if we're running in a cargo-vendor'd environment? I'm not sure if that's exposed to build.rs.

**Comment by sorpaas** [comment]
I'm going to reopen this issue. `ring` build breaks again on the current glibc NixOS is using (for nixos-unstable).

**Comment by akru** [comment]
@sorpaas Yes, as I see, parity fork of `ring` packages are merged with upstream and my hack disabled.

@briansmith What you think about using environment variable (flag) to enabling use of pregenerated asms? Because using of pregenerated files by default is not so good, as we can see in this case.

**Comment by c0gent** [comment]
@akru, can you fill me in on what needs to be done to get ring back onto the release pipeline? I need to update everything to ring 0.13 in order to update hyper, etc.
