### ISSUE TITLE
Parity crashing with no error message

### ISSUE THREAD

**Issue by quantumproducer** [paritytech/parity-ethereum#8905]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.11.3 beta
> - **Which operating system?**: Linux
> - **How installed?**: source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: Ether
> - **Did you try to restart the node?**: yes

I connected to my server and found this:

```
MiB db 266 KiB queue 99 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-06-08 21:42:00 UTC Syncing #5755525 0x1b83…7fc5     0 blk/s    0 tx/s   0 Mgas/s      9+    1 Qed  #5755536    2/25 peers   3 MiB chain 107 MiB db 266 KiB queue 99 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-06-08 21:45:08 UTC Imported #5755536 0xbd17…b9be (27 txs, 7.98 Mgas, 1266.00 ms, 17.67 KiB)
2018-06-08 21:49:49 UTC    2/25 peers   5 MiB chain 105 MiB db 0 bytes queue 99 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-06-08 21:49:49 UTC    2/25 peers   5 MiB chain 105 MiB db 0 bytes queue 99 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-06-08 21:49:49 UTC Imported #5755561 0x8865…f6e7 (116 txs, 4.83 Mgas, 1620.84 ms, 15.22 KiB)
2018-06-08 21:49:49 UTC    2/25 peers   5 MiB chain 105 MiB db 0 bytes queue 99 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-06-08 21:52:14 UTC Imported #5755568 0xd291…f335 (68 txs, 7.98 Mgas, 1448.85 ms, 25.33 KiB)
```

so I restarted it, because it wasn't running. Why is there no error message? How do I tell why it crashed? Can I make parity automatically restart or do I need to use a bash script for that?

```
root@tunnel:~# parity --db-path=/mnt/tryit --pruning=fast --warp
Option '--warp' does nothing. It's on by default.
2018-06-15 02:14:12 UTC Starting Parity/v1.11.3-beta-a66e36b-20180605/x86_64-linux-gnu/rustc1.26.1
2018-06-15 02:14:12 UTC Keys path /root/.local/share/io.parity.ethereum/keys/Foundation
2018-06-15 02:14:12 UTC DB path /mnt/tryit/ethereum/db/906a34e69aec8c0d
2018-06-15 02:14:12 UTC Path to dapps /root/.local/share/io.parity.ethereum/dapps
```

started up again just fine

**Comment by Tbaut** [comment]
Thanks for the report. If you can manage to reproduce it, could you tell if any of your memory or CPU is at 100%?

There is no other way to restart parity automatically than with external tools (such as systemd).

**Comment by Njcrypto** [comment]
I believe this is related to the open file issue. Same symptom.

**Comment by Tbaut** [comment]
Related https://github.com/paritytech/parity/issues/8813 ?
@Njcrypto I'd expect parity to give an error message on this one...

**Comment by alexcos20** [comment]
Could be related to [](https://github.com/paritytech/parity/issues/8908) ?

As soon as the messages dissapered, parity is fine for over 24 hours now..

**Comment by vnistor** [comment]
Since updating to branches 1.10 and 1.11, our Ropsten node keeps crashing without an error.  Seems to have gotten worse in 1.11.4-beta. In 1.11.3 it would run for a few hours. Now it doesn't even last 1 minute.
5 < RPC / second.
While running in DEBUG, one of the last messages displayed is:
`dapps  Handling endpoint request: (None, None), referer: None`
We have 
```[dapps]
# You won't be able to access any web Dapps.
disable = true```

**Comment by Tbaut** [comment]
@vnistor  Can you please tell us more about your configuration?

**Comment by vnistor** [comment]
Running inside a public subnet in AWS.

```
# This config should be placed in following path:
#   ~/.local/share/io.parity.ethereum/config.toml

[parity]
auto_update = "all"
release_track = "beta"
chain = "ropsten"
base_path = "/home/ubuntu/chains/io.parity.ethereum"

[ui]
disable = true

[network]
min_peers = 200
max_peers = 200
snapshot_peers = 50
max_pending_peers = 200

[rpc]
interface = internal VPC IP
hosts = ["all"]
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "net", "parity", "traces", "rpc"]

[websockets]
disable = true

[ipc]
disable = true

[dapps]
# You won't be able to access any web Dapps.
disable = true

[footprint]
# Keep all state trie data. No pruning.
pruning = "archive"
# Compute and Store tracing data. (Enables trace_* APIs).
tracing = "on"

**Comment by vnistor** [comment]
`DEBUG before crash:`

```
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop process - 2 events, Duration { secs: 0, nanos: 549871 }
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop poll - Duration { secs: 0, nanos: 1495 }
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop time - Instant { tv_sec: 21593679, tv_nsec: 485501 }
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop process - 0 events, Duration { secs: 0, nanos: 16269 }
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop poll - Duration { secs: 0, nanos: 142680 }
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop time - Instant { tv_sec: 21593679, tv_nsec: 651897 }
2018-06-22 15:18:43 UTC  DEBUG tokio_proto::streaming::pipeline::advanced  write in body done
2018-06-22 15:18:43 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x349367","id":15}.
2018-06-22 15:18:43 UTC  DEBUG tokio_proto::streaming::pipeline::advanced  write in body done
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  scheduling direction for: 3
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  blocking
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop process - 1 events, Duration { secs: 0, nanos: 115148 }
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop poll - Duration { secs: 0, nanos: 1194 }
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop time - Instant { tv_sec: 21593679, tv_nsec: 776314 }
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop process - 0 events, Duration { secs: 0, nanos: 14775 }
2018-06-22 15:18:43 UTC IO Worker #0 DEBUG network  Connecting peers: 15 sessions, 27 pending + 32 started
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop poll - Duration { secs: 0, nanos: 120794285 }
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop time - Instant { tv_sec: 21593679, tv_nsec: 121592527 }
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  notifying a task handle
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop process - 1 events, Duration { secs: 0, nanos: 107843 }
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop poll - Duration { secs: 0, nanos: 4637 }
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop time - Instant { tv_sec: 21593679, tv_nsec: 121714340 }
2018-06-22 15:18:43 UTC  DEBUG dapps  Handling endpoint request: (None, None), referer: None
2018-06-22 15:18:43 UTC  DEBUG tokio_proto::streaming::pipeline::advanced  sending a chunk
2018-06-22 15:18:43 UTC  DEBUG tokio_proto::streaming::pipeline::advanced  immediately done
2018-06-22 15:18:43 UTC  DEBUG tokio_proto::streaming::pipeline::advanced  write in body done
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop process - 1 events, Duration { secs: 0, nanos: 163280 }
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop poll - Duration { secs: 0, nanos: 1270 }
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop time - Instant { tv_sec: 21593679, tv_nsec: 121894317 }
2018-06-22 15:18:43 UTC  DEBUG tokio_core::reactor  loop process - 0 events, Duration { secs: 0, nanos: 14862 }
```

**Comment by 5chdn** [comment]
Is there anything in system logs? dmesg?

**Comment by vnistor** [comment]
@5chdn I found these in apport.log today:
```
ERROR: apport (pid 8256) Tue Jul 10 09:58:10 2018: called for pid 8076, signal 6, core limit 0, dump mode 1
ERROR: apport (pid 8256) Tue Jul 10 09:58:10 2018: executable: /usr/bin/parity (command line "parity daemon daemon.ropsten -l INFO --log-file log.ropsten --config config.toml --ntp-servers 169.254.169.123")
ERROR: apport (pid 8256) Tue Jul 10 09:58:10 2018: is_closing_session(): no DBUS_SESSION_BUS_ADDRESS in environment
ERROR: apport (pid 8256) Tue Jul 10 09:58:10 2018: apport: report /var/crash/_usr_bin_parity.1000.crash already exists and unseen, doing nothing to avoid disk usage DoS
```

**Comment by vnistor** [comment]
Running v1.11.6-beta non-deamonized:
```
parity -l INFO --log-file log.ropsten --config config.toml --ntp-servers 169.254.169.123
Loading config file from config.toml
2018-07-10 14:32:45 UTC Starting Parity/v1.11.6-beta-4ba600f-20180709/x86_64-linux-gnu/rustc1.27.0
2018-07-10 14:32:45 UTC Keys path /home/ubuntu/chains/io.parity.ethereum/keys/Ropsten
2018-07-10 14:32:45 UTC DB path /home/ubuntu/chains/io.parity.ethereum/chains/test/db/ae90623718e47d66
2018-07-10 14:32:45 UTC Path to dapps /home/ubuntu/chains/io.parity.ethereum/dapps
2018-07-10 14:32:45 UTC State DB configuration: archive +Fat +Trace
2018-07-10 14:32:45 UTC Operating mode: active
2018-07-10 14:32:45 UTC Warning: Warp Sync is disabled because Fat DB is turned on.
2018-07-10 14:32:45 UTC Configured for Ropsten using Ethash engine
2018-07-10 14:32:45 UTC Public node URL: enode://391792dc9f4d695f8f3b8b577f1fcef611d554b8b1667bf4002ebad53bc4a452d00095141ca44bb97c0a7971dee39ec0fbaebd886a0ebdfa7c7e0d8bce2e07da@34.241.5.44:30303
2018-07-10 14:32:45 UTC Removed existing file '/home/ubuntu/chains/io.parity.ethereum/jsonrpc.ipc'.

====================

stack backtrace:
   0:     0x563f3ea3f38c - <no info>

Thread '<unnamed>' panicked at 'View rlp is trusted and should be valid. Constructed in ethcore/src/encoded.rs on line 202: RlpExpectedToBeData', ethcore/src/views/view_rlp.rs:56

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)
```

**Comment by vnistor** [comment]
Running v1.10.9-stable non-deamonized:
```
$ parity -l INFO --log-file log.ropsten --config config.toml --ntp-servers 169.254.169.123
Loading config file from config.toml
2018-07-10 14:40:52 UTC Starting Parity/v1.10.9-stable-23a9eef-20180707/x86_64-linux-gnu/rustc1.27.0
2018-07-10 14:40:52 UTC Keys path /home/ubuntu/chains/io.parity.ethereum/keys/Ropsten
2018-07-10 14:40:52 UTC DB path /home/ubuntu/chains/io.parity.ethereum/chains/test/db/ae90623718e47d66
2018-07-10 14:40:52 UTC Path to dapps /home/ubuntu/chains/io.parity.ethereum/dapps
2018-07-10 14:40:52 UTC State DB configuration: archive +Fat +Trace
2018-07-10 14:40:52 UTC Operating mode: active
2018-07-10 14:40:52 UTC Warning: Warp Sync is disabled because Fat DB is turned on.
2018-07-10 14:40:52 UTC Configured for Ropsten using Ethash engine
2018-07-10 14:40:52 UTC Public node URL: enode://391792dc9f4d695f8f3b8b577f1fcef611d554b8b1667bf4002ebad53bc4a452d00095141ca44bb97c0a7971dee39ec0fbaebd886a0ebdfa7c7e0d8bce2e07da@myip:30303
2018-07-10 14:40:54 UTC Removed existing file '/home/ubuntu/chains/io.parity.ethereum/jsonrpc.ipc'.
2018-07-10 14:40:59 UTC Syncing #3555976 e214â¦146b     1 blk/s   79 tx/s   5 Mgas/s   2147+    1 Qed  #3558125    5/200 peers   758 KiB chain 252 KiB db 32 MiB queue 6 MiB sync  RPC:  0 conn,  1 req/s,  75 Âµs

====================

stack backtrace:
   0:     0x55fdf75ee67c - <no info>

Thread '<unnamed>' panicked at 'Unexpected rlp error: RlpExpectedToBeData', libcore/result.rs:945

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)
```

**Comment by vnistor** [comment]
This might be what was happening before or not. The error is only printed when not running daemonized, so no way to know really, as I was running daemonized before.

**Comment by debris** [comment]
I analysed the code and this is clearly an issue with our rlp views and verification of *external* data. Thanks @vnistor for this awesome report

**Comment by Tbaut** [comment]
Could you see this behaviour on a recent release? Happy to reopen.
