### ISSUE TITLE
archivedb assertion on when syncing and launch

### ISSUE THREAD

**Issue by computerality** [paritytech/parity-ethereum#9180]
> I'm running:
>
> - **Which Parity version?**: 2.0.0 beta
> - **Which operating system?**:  Linux
> - **How installed?**:binaries 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

I'm running parity with the following arguments:
`./parity  --no-ipc --pruning=archive --tracing=on --fat-db=on`

An assertion happened in util/journaldb/src/archivedb.rs while syncing and now happens every time parity is launched using the dame data dir.

```
2018-07-21 01:53:39  Syncing #1589194 0x19d5…cf87    73.32 blk/s  434.9 tx/s   15 Mgas/s    754+  806 Qed  #1590761    3/50 peers   223 MiB chain 69 MiB db 8 MiB queue 6 MiB sync  RPC:  0 conn,    0 req/s,    0 µs

====================

stack backtrace:
   0:     0x7fcecbb8964c - <no info>
   1:     0x7fcecbb88c12 - <no info>
   2:     0x7fcecbb8816a - <no info>
   3:     0x7fceca710a85 - <no info>
   4:     0x7fcecbbe4d55 - <no info>
   5:     0x7fcecbbb0a16 - <no info>
   6:     0x7fcecbbb00dd - <no info>
   7:     0x7fcecb2bccc5 - <no info>
   8:     0x7fcecb1b9284 - <no info>
   9:     0x7fcecaefba1b - <no info>
  10:     0x7fcecaf182f3 - <no info>
  11:     0x7fcecaefc7fc - <no info>
  12:     0x7fcecaf021d6 - <no info>
  13:     0x7fcecbc10199 - <no info>
  14:     0x7fcecaf16228 - <no info>
  15:     0x7fcecbc015ba - <no info>
  16:     0x7fcecbbe5365 - <no info>
  17:     0x7fcec94376b9 - <no info>
  18:     0x7fcec8f4741c - <no info>
  19:                0x0 - <no info>

Thread 'IO Worker #1' panicked at 'assertion failed: rc == -1', util/journaldb/src/archivedb.rs:141


2018-07-21 01:53:44  Finishing work, please wait...
2018-07-21 01:53:44  Block import failed for #1590282 (0xcb85…b1d0): Parent not found (0x680d…aaa9)
```
When running with -l debug, the following are a few debug messages before the assertion:
```
2018-07-21 08:10:32  Verifier #0 DEBUG trace  Traced call FlatTrace { action: Call(Call { from: 0x86ee51df9db214218cbb1b73aebe3c159000096e, to: 0xa0c446bd3d10dc375523bc56be956a6b54b2964a, value: 0x0, gas: 0xd43a5, input: [161, 173, 213, 16, 101, 108, 99, 111, 105, 110, 80, 111, 84, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 101, 108, 99, 111, 105, 110, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 254, 26, 150, 205, 11, 251, 50, 69, 216, 56, 8, 185, 171, 166, 83, 133, 118, 20, 89, 32], call_type: Call }), result: Call(CallResult { gas_used: 0x812, output: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1] }), subtraces: 0, trace_address: [] }
2018-07-21 08:10:32  Verifier #0 DEBUG trace  Traced call FlatTrace { action: Call(Call { from: 0xfe1a96cd0bfb3245d83808b9aba6538576145920, to: 0x86ee51df9db214218cbb1b73aebe3c159000096e, value: 0x0, gas: 0xda8df, input: [190, 171, 172, 200, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 6, 12, 215, 138, 125, 47, 158, 218, 145, 28, 243, 225, 54, 140, 248, 30, 109, 109, 144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 164, 75, 102, 60, 162, 187, 240, 177, 154, 118, 146, 95, 14, 231, 33, 91, 174, 36, 170, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 105, 80], call_type: Call }), result: Call(CallResult { gas_used: 0x5cea, output: [] }), subtraces: 1, trace_address: [] }
2018-07-21 08:10:32  Verifier #0 DEBUG trace  Traced call FlatTrace { action: Call(Call { from: 0x97740f3239ead47a78df7eb68b9402ac618b454c, to: 0x70060cd78a7d2f9eda911cf3e1368cf81e6d6d90, value: 0x7fb4552f3d000, gas: 0x8fc, input: [], call_type: Call }), result: Call(CallResult { gas_used: 0x0, output: [] }), subtraces: 0, trace_address: [] }
2018-07-21 08:10:32  Verifier #0 DEBUG trace  Traced call FlatTrace { action: Call(Call { from: 0xfe1a96cd0bfb3245d83808b9aba6538576145920, to: 0x97740f3239ead47a78df7eb68b9402ac618b454c, value: 0x0, gas: 0xd49f7, input: [243, 254, 243, 163, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 6, 12, 215, 138, 125, 47, 158, 218, 145, 28, 243, 225, 54, 140, 248, 30, 109, 109, 144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 251, 69, 82, 243, 208, 0], call_type: Call }), result: Call(CallResult { gas_used: 0x1cda, output: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1] }), subtraces: 1, trace_address: [] }
2018-07-21 08:10:32  Verifier #0 DEBUG trace  Traced call FlatTrace { action: Call(Call { from: 0x70060cd78a7d2f9eda911cf3e1368cf81e6d6d90, to: 0xfe1a96cd0bfb3245d83808b9aba6538576145920, value: 0x1, gas: 0xee868, input: [169, 5, 156, 187, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 164, 75, 102, 60, 162, 187, 240, 177, 154, 118, 146, 95, 14, 231, 33, 91, 174, 36, 170, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 105, 80], call_type: Call }), result: Call(CallResult { gas_used: 0x15a32, output: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1] }), subtraces: 10, trace_address: [] }
2018-07-21 08:10:32  Verifier #0 DEBUG trace  Traced reward FlatTrace { action: Reward(Reward { author: 0x4bb96091ee9d802ed039c4d1a5f6216f90f81b01, value: 0x4563918244f40000, reward_type: Block }), result: None, subtraces: 0, trace_address: [] }
```
And the following messages appear after the assertion/report message:
```
2018-07-21 08:10:32  IO Worker #2 DEBUG sync  0 -> Dispatching packet: 6
2018-07-21 08:10:32  main INFO parity_ethereum::run  Finishing work, please wait...
2018-07-21 08:10:32  Verifier #7 WARN client  Block import failed for #1590285 (0x710b…752e): Parent not found (0xa0d1…54d6)
2018-07-21 08:10:32  IO Worker #2 DEBUG sync  Bad block 0xbe34acf1972699ad420e914802924f7fd536b73d1d0590dae5fbfd804b090c28 : BlockImportError(Import(KnownBad), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
2018-07-21 08:10:32  main DEBUG local_store  Updating node data store on shutdown.
```

**Comment by Tbaut** [comment]
@debris can you have a look at this one?

**Comment by debris** [comment]
@computerality is it possible for you to compile from scratch and run a debug version of parity? So we could see the full backtrace :)

**Comment by computerality** [comment]
```stack backtrace:
   0:     0x55f4ad26c88c - backtrace::backtrace::trace::h27488b79d275bd7a
   1:     0x55f4ad26be52 - backtrace::capture::Backtrace::new::hb914cbf52847b894
   2:     0x55f4ad26b3aa - panic_hook::panic_hook::hcf023c6f466bd402
   3:     0x55f4abdf36d5 - panic_hook::set_with::{{closure}}::ha3fa7a9368219ac4
   4:     0x55f4ad2c7105 - std::panicking::rust_panic_with_hook::h6617a62274b53c0e
                        at libstd/panicking.rs:467
   5:     0x55f4ad292dc6 - std::panicking::begin_panic::h3a478869342ee500
   6:     0x55f4ad29248d - <journaldb::archivedb::ArchiveDB as journaldb::traits::JournalDB>::journal_under::hc05225fbe31f1f75
   7:     0x55f4ac99fc95 - ethcore::state_db::StateDB::journal_under::h47379c36717f3fad
   8:     0x55f4ac89c254 - _ZN7ethcore6client6client8Importer22import_verified_blocks17hc82f4468e160a8c6E.llvm.2983238308959723688
   9:     0x55f4ac5deaab - <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message::h9deb00b38b7561a8
  10:     0x55f4ac5fb383 - ethcore_io::worker::Worker::work_loop::h3fc2e24316f7a39f
  11:     0x55f4ac5df7ec - std::sys_common::backtrace::__rust_begin_short_backtrace::hc077a829888d74a8
  12:     0x55f4ac5e5266 - _ZN3std9panicking3try7do_call17he2c3a29233ff710bE.llvm.668224595337482288
  13:     0x55f4ad2f2549 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  14:     0x55f4ac5f8f48 - <F as alloc::boxed::FnBox<A>>::call_box::h579c728383542c12
  15:     0x55f4ad2e396a - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::hf39b44b24afa9ef1
                        at /checkout/src/liballoc/boxed.rs:648
                         - std::sys_common::thread::start_thread::h4ed3fc1b29049f2d
                        at libstd/sys_common/thread.rs:24
  16:     0x55f4ad2c7715 - std::sys::unix::thread::Thread::new::thread_start::hbee9c01696d35c87
                        at libstd/sys/unix/thread.rs:90
  17:     0x7f24d773c6da - start_thread
  18:     0x7f24d724d88e - __clone
  19:                0x0 - <unknown>```

**Comment by computerality** [comment]
This also seems to reproduce on 1.11.7. Looks like it happened around a similar block number too.

**Comment by weijiekoh** [comment]
I can confirm this.

```
2018-11-08 18:10:43  Syncing #1589717 0x800a…f107     4.72 blk/s   76.3 tx/s    2 Mgas/s      0+ 6097 Qed  #1595818   26/50 peers   6 MiB chain 17 MiB db 41 MiB queue 10 MiB sync  RPC:  0 conn,    0 req/s,    0 µs

====================

stack backtrace:
   0:     0x562815322f0c - <no info>
   1:     0x5628153221a2 - <no info>
   2:     0x562815322218 - <no info>
   3:     0x56281532101a - <no info>
   4:     0x562813da5705 - <no info>
   5:     0x56281537ecd3 - <no info>
   6:     0x562815335926 - <no info>
   7:     0x56281534bd89 - <no info>
   8:     0x562814a5d7d2 - <no info>
   9:     0x562814a1cafd - <no info>
  10:     0x5628146f76ec - <no info>
  11:     0x5628147142a1 - <no info>
  12:     0x5628146f2340 - <no info>
  13:     0x5628146fbc86 - <no info>
  14:     0x5628153aab99 - <no info>
  15:     0x562814702262 - <no info>
  16:     0x562815398a2a - <no info>
  17:     0x56281537f4f5 - <no info>
  18:     0x7f74a3d386da - <no info>
  19:     0x7f74a384988e - <no info>
  20:                0x0 - <no info>

Thread 'IO Worker #2' panicked at 'assertion failed: rc == -1', util/journaldb/src/archivedb.rs:141

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

2018-11-08 18:10:52  Finishing work, please wait...
2018-11-08 18:10:52  Block import failed for #1590282 (0xcb85…b1d0): Parent not found (0x680d…aaa9)
```

**Comment by joshua-mir** [comment]
@weijiekoh can you share what version of parity you are using, your platform, and what flags you are launching parity with?

**Comment by weijiekoh** [comment]
`./parity --db-path=mainnet --no-ws --no-dapps --pruning=archive --fat-db=on --chain=mainnet --identity=blahblah9234875 --port 30304`
`version Parity-Ethereum/v2.0.9-stable-09f7757-20181028/x86_64-linux-gnu/rustc1.30.0`
Ubuntu 18.04.1 LTS
Linux 4.15.0-38-generic 
x86_64
