### ISSUE TITLE
byte index 2 is not a char boundary.(bug)

### ISSUE THREAD

**Issue by mahuaibo** [paritytech/parity-ethereum#9233]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**:  Linux
> - **How installed?**: via installer / homebrew / binaries / from source
> - **Are you fully synchronized?**: no / yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
> - **Did you try to restart the node?**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
=========================================================================
Thread '<unnamed>' panicked at 'byte index 2 is not a char boundary; it is inside '锅' (bytes 0..3) of `锅煸豆腐`', libcore/str/mod.rs:2266

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new

2018-07-27 08:34:43 UTC Finishing work, please wait...
=========================================================================

**Comment by Tbaut** [comment]
Can you please describe what you were doing, what parity version, etc (edit your first post)

**Comment by mahuaibo** [comment]
IMAGE ID: "parity/parity"  0a0fa44fe677

The main reason is that the Chinese character set is not supported

**Comment by sorpaas** [comment]
Looks like we're not handling UTF-8 correctly. @mahuaibo Do you mind to do a search to see where this phrase `锅煸豆腐` comes from (i.e. config files or key metadata)?

**Comment by mahuaibo** [comment]
When a get Transaction or Block is encoded using an illegal utf-8 encode, it is not normally processed.

**Comment by sorpaas** [comment]
@mahuaibo Would you mind providing an example of such block/transaction?

**Comment by Vurich** [comment]
Can you recreate this bug with the `RUST_BACKTRACE` environment variable set to 1? On Linux you would do this with:

```bash
env RUST_BACKTRACE=1 parity
```

If you run Parity Ethereum with extra command-line flags you would add them after `parity`.

**Comment by strangeman** [comment]
We have the same issue.

- Parity 2.0.9 (launched in Docker)
- Centos 7, Docker 17.05.0-ce

Config:
```
# This config should be placed in following path:
#   ~/.local/share/io.parity.ethereum/config.toml
[parity]

[rpc]
#  JSON-RPC will be listening for connections on IP 0.0.0.0.
interface = "0.0.0.0"

[websockets]
#  JSON-RPC will be listening for connections on IP 0.0.0.0.
interface = "0.0.0.0"

[network]
# Parity will sync by downloading latest state first. Node will be operational in couple minutes.
warp = false

[footprint]
db_compaction = "ssd"
# Keep all state trie data. No pruning.
pruning = "archive"
# Enables Fat DB
fat_db = "on"
```

Crash backtrace:
```
фев 04 03:56:04 prod55 docker[22016]: 2019-02-04 00:56:04 UTC Public node URL: enode://c55031495a621b23583b4dc5fa382fe0fd01f32939ec862a28f04d2df9f7a37ba19ad6d11035fc24c08a2a3ab3de582e631f4fae7552e541859617cd39f1071d@172.17.0.2:30303
фев 04 03:56:08 prod55 docker[22016]: ====================
фев 04 03:56:08 prod55 docker[22016]: stack backtrace:
фев 04 03:56:08 prod55 docker[22016]: 0:     0x5609294d8f0c - <no info>
фев 04 03:56:08 prod55 docker[22016]: 1:     0x5609294d81a2 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 2:     0x5609294d8218 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 3:     0x5609294d701a - <no info>
фев 04 03:56:08 prod55 docker[22016]: 4:     0x560927f5b705 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 5:     0x560929534cd3 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 6:     0x560929534839 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 7:     0x560929534735 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 8:     0x56092958d31b - <no info>
фев 04 03:56:08 prod55 docker[22016]: 9:     0x56092958f73f - <no info>
фев 04 03:56:08 prod55 docker[22016]: 10:     0x560928204430 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 11:     0x56092820fc45 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 12:     0x5609281a9b2e - <no info>
фев 04 03:56:08 prod55 docker[22016]: 13:     0x5609280d10b2 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 14:     0x56092808b669 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 15:     0x560927f2c767 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 16:     0x560927ee4717 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 17:     0x560927fddd60 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 18:     0x560928189ea8 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 19:     0x56092817b2ef - <no info>
фев 04 03:56:08 prod55 docker[22016]: 20:     0x56092816ddd4 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 21:     0x56092815632f - <no info>
фев 04 03:56:08 prod55 docker[22016]: 22:     0x560929560b99 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 23:     0x5609280ff9ba - <no info>
фев 04 03:56:08 prod55 docker[22016]: 24:     0x560928149fc3 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 25:     0x56092941b90d - <no info>
фев 04 03:56:08 prod55 docker[22016]: 26:     0x56092941ba6e - <no info>
фев 04 03:56:08 prod55 docker[22016]: 27:     0x5609294130f1 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 28:     0x560929414489 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 29:     0x560929414d34 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 30:     0x560929560b99 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 31:     0x560929414ba0 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 32:     0x56092954ea2a - <no info>
фев 04 03:56:08 prod55 docker[22016]: 33:     0x5609295354f5 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 34:     0x7f1243aac6b9 - <no info>
фев 04 03:56:08 prod55 docker[22016]: 35:     0x7f12435cc41c - <no info>
фев 04 03:56:08 prod55 docker[22016]: 36:                0x0 - <no info>
фев 04 03:56:08 prod55 docker[22016]: Thread '<unnamed>' panicked at 'byte index 2 is not a char boundary; it is inside '∀' (bytes 0..3) of `∀∂∈∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∂∈ℝ∧∪≡∞ ↑↗↨↻⇣ ┐┼╔╘░►☺♀ ﬁ�⑀₂ἠḂӥẄɐː⍎אԱა \n && ';1'23,12;'312:L:!\" &&  ∂`[...]', libcore/str/mod.rs:2111
фев 04 03:56:08 prod55 docker[22016]: This is a bug. Please report it at:
фев 04 03:56:08 prod55 docker[22016]: https://github.com/paritytech/parity/issues/new
фев 04 03:56:08 prod55 docker[22016]: 2019-02-04 00:56:08 UTC Finishing work, please wait...
```

Parity crashes at random, sometimes after 1-2 minutes after start, sometimes - after 3-4 hours.

**Comment by joshua-mir** [comment]
This issue has been resolved by the latest release #10287 for more information.

**Comment by strangeman** [comment]
@joshua-mir seems working, thank you!
