### ISSUE TITLE
Parity node stopped

### ISSUE THREAD

**Issue by ekulaleba** [paritytech/parity-ethereum#9376]
> I'm running:
>
> - **Which Parity version?**: 2.1.0
> - **Which operating system?**: Linux (Ubuntu 18.04)
> - **How installed?**: via snapcraft
> - **Are you fully synchronized?**: Yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

Restarting the node did resume syncing without any problems
```

stack backtrace:
   0:     0x5625bdadd0fc - backtrace::backtrace::trace::h2cf9faf3ffdef8b6
   1:     0x5625bdadb882 - backtrace::capture::Backtrace::new::hb16d4368855174bc
   2:     0x5625bdadb1fe - panic_hook::gen_panic_msg::he8c83a8ed6ad40ee
   3:     0x5625bc69ab47 - panic_hook::set_with::{{closure}}::h5faf80ac951931a1
   4:     0x5625bdb4b4c9 - std::panicking::rust_panic_with_hook::habacef8c65a3b0d4
                        at libstd/panicking.rs:403
   5:     0x5625bdb4b2b2 - std::panicking::begin_panic_fmt::h20e14b91a98870b3
                        at libstd/panicking.rs:349
   6:     0x5625bdb4b1e2 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x5625bdb9d710 - core::panicking::panic_fmt::h8a30aa26a6a035a8
                        at libcore/panicking.rs:72
   8:     0x5625bd2fd0d8 - core::result::unwrap_failed::h91b6374d396912e5
   9:     0x5625bd224c15 - ethcore::blockchain::blockchain::BlockChain::prepare_update::h1a03f93eadd302d0
  10:     0x5625bd223828 - ethcore::blockchain::blockchain::BlockChain::insert_block_with_route::h821f5a1c74ee7f77
  11:     0x5625bd221834 - ethcore::blockchain::blockchain::BlockChain::insert_block::h79c2fedd94f78dc6
  12:     0x5625bd329827 - _ZN7ethcore6client6client8Importer22import_verified_blocks17h4e277391bcc3d3a7E.llvm.9506622231012940841
  13:     0x5625bcde9b69 - <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message::h5b75b969a6137cec
  14:     0x5625bd1c592c - <ethcore_io::service_mio::IoChannel<Message>>::send_sync::h55df953116a0f697
  15:     0x5625bd08cd83 - ethcore::verification::queue::QueueSignal::set_sync::hdafd8c737fa872ea
  16:     0x5625bd08f284 - <ethcore::verification::queue::VerificationQueue<K>>::verify::h4dcdde6ac94a6c4e
  17:     0x5625bd11139a - std::sys_common::backtrace::__rust_begin_short_backtrace::ha11bb3df155ac5f6
  18:     0x5625bd1e06bd - std::panicking::try::do_call::h5091394376cd0a7b
  19:     0x5625bdb6068e - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  20:     0x5625bd1f078f - <F as alloc::boxed::FnBox<A>>::call_box::haf382bc74e661c9e
  21:     0x5625bdb55577 - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h4b3bd62cb4ac177f
                        at /checkout/src/liballoc/boxed.rs:794
                         - std::sys_common::thread::start_thread::h0b7f53596953c14b
                        at libstd/sys_common/thread.rs:24
  22:     0x5625bdb3b338 - std::sys::unix::thread::Thread::new::thread_start::hce65be213f90eb53
                        at libstd/sys/unix/thread.rs:90
  23:     0x7f420ab9f6b9 - start_thread
  24:     0x7f420a6be41c - clone
  25:                0x0 - <unknown>

Thread 'Verifier #1' panicked at 'Low level database error when updating blooms. Some issue with disk?: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', libcore/result.rs:945

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new

2018-08-18 03:03:59  Finishing work, please wait...2018-08-18 03:04:01  Error creating node table file: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

====================

stack backtrace:
   0:     0x5625bdadd0fc - backtrace::backtrace::trace::h2cf9faf3ffdef8b6
   1:     0x5625bdadb882 - backtrace::capture::Backtrace::new::hb16d4368855174bc
   2:     0x5625bdadb1fe - panic_hook::gen_panic_msg::he8c83a8ed6ad40ee
   3:     0x5625bc69ab47 - panic_hook::set_with::{{closure}}::h5faf80ac951931a1
   4:     0x5625bdb4b4c9 - std::panicking::rust_panic_with_hook::habacef8c65a3b0d4
                        at libstd/panicking.rs:403
   5:     0x5625bdb4b2b2 - std::panicking::begin_panic_fmt::h20e14b91a98870b3
                        at libstd/panicking.rs:349
   6:     0x5625bdb4b1e2 - rust_begin_unwind
                        at libstd/panicking.rs:325
   7:     0x5625bdb9d710 - core::panicking::panic_fmt::h8a30aa26a6a035a8
                        at libcore/panicking.rs:72
   8:     0x5625bc5253df - core::result::unwrap_failed::h92efc18743446c23
   9:     0x5625bc47516b - <ethcore::verification::queue::VerificationQueue<K> as core::ops::drop::Drop>::drop::ha06e80118d3273b8
  10:     0x5625bc7153a0 - core::ptr::drop_in_place::h8a67ed8e59fe2916
  11:     0x5625bc71a4a3 - core::ptr::drop_in_place::hdd5b290179b3aca6
  12:     0x5625bce26949 - <alloc::arc::Arc<T>>::drop_slow::h29fffc800ba6f8d7
  13:     0x5625bcac4dc9 - <alloc::arc::Arc<T>>::drop_slow::h26dcd164e9e9257a
  14:     0x5625bcadfc64 - core::ptr::drop_in_place::h83ffe488e619d00a
  15:     0x5625bcaceab2 - <alloc::arc::Arc<T>>::drop_slow::he1b39fc6833e7db6
  16:     0x5625bca17f8d - core::ptr::drop_in_place::hd9a5d06e43f815ad
  17:     0x5625bc636209 - <alloc::arc::Arc<T>>::drop_slow::h536d655d6fda4b37
  18:     0x5625bc635e1e - <alloc::arc::Arc<T>>::drop_slow::h4773a40c91d8b959
  19:     0x5625bc63cef9 - <alloc::arc::Arc<T>>::drop_slow::hce954095612f5757
  20:     0x5625bc6ebda6 - <std::collections::hash::table::RawTable<K, V> as core::ops::drop::Drop>::drop::h0e0fcc25a323a10f
  21:     0x5625bc635851 - <alloc::arc::Arc<T>>::drop_slow::h44347aa2ab26cab3
  22:     0x5625bc5201cb - core::ptr::drop_in_place::hb477cce99508ae31
  23:     0x5625bd78c50a - tokio::executor::current_thread::scheduler::release_node::h8685b86c2f5e114a
  24:     0x5625bd7804dd - core::ptr::drop_in_place::h2555661fd1ef5363
  25:     0x5625bd77ff17 - std::sys_common::backtrace::__rust_begin_short_backtrace::he8669668c835cbfd
  26:     0x5625bd78012b - _ZN3std9panicking3try7do_call17h213d373b08e50ac7E.llvm.17302108555529141984
  27:     0x5625bdb6068e - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  28:     0x5625bd788e9c - <F as alloc::boxed::FnBox<A>>::call_box::h5472c027073470d1
  29:     0x5625bdb55577 - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h4b3bd62cb4ac177f
                        at /checkout/src/liballoc/boxed.rs:794
                         - std::sys_common::thread::start_thread::h0b7f53596953c14b
                        at libstd/sys_common/thread.rs:24
  30:     0x5625bdb3b338 - std::sys::unix::thread::Thread::new::thread_start::hce65be213f90eb53
                        at libstd/sys/unix/thread.rs:90
  31:     0x7f420ab9f6b9 - start_thread
  32:     0x7f420a6be41c - clone
  33:                0x0 - <unknown>

Thread '<unnamed>' panicked at 'Propagating verifier thread panic on shutdown: Any', libcore/result.rs:945

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new
```

**Comment by debris** [comment]
it's interesting. looks like 2 threads at the same time were unable to access filesystem (`Permission denied`). I honestly don't know and doubt we can do anything about this. @andresilva do you have any guess what could happen in this case? If not, I'd just close the issue

**Comment by ekulaleba** [comment]
I know right, I can't even reproduce it on command, it happens randomly with no reason whatsoever. Since its not a problematic issue as the node can be restarted and everything is fine you can close it from my end. I only reported it it because I thought I should.
