### ISSUE TITLE
Thread 'IO Worker #0' panicked at 'Cannot operate with an empty validator set.', ethcore/src/engines/validator_set/simple_list.rs:96

### ISSUE THREAD

**Issue by Hann** [paritytech/parity-ethereum#9478]
- **Parity Ethereum version**: v2.0.3-beta-a0a2bed-20180831/x86_64-macos/rustc1.28.0
- **Operating system**: MacOS 
- **Installation**: homebrew
- **Fully synchronized**: no
- **Network**: private network
- **Restarted**: yes

**steps**
1. I tried to copy and paste the link https://wiki.parity.io/Demo-PoA-tutorial until this section https://wiki.parity.io/Demo-PoA-tutorial#5-connecting-the-nodes 
1. i just changed addresses in all config file and `accounts` param in `demo-spec.json`.

**actual**

```
$ parity --config node0.toml
Loading config file from node0.toml
2018-09-05 15:06:40  Starting Parity-Ethereum/v2.0.3-beta-a0a2bed-20180831/x86_64-macos/rustc1.28.0
2018-09-05 15:06:40  Keys path /Users/user/Documents/parity_eth/account_node0/keys/DemoPoA
2018-09-05 15:06:40  DB path /Users/user/Documents/parity_eth/account_node0/chains/DemoPoA/db/8e905fb8cdbd53f7
2018-09-05 15:06:40  State DB configuration: fast
2018-09-05 15:06:40  Operating mode: active
2018-09-05 15:06:40  Configured for DemoPoA using AuthorityRound engine

====================

stack backtrace:
   0:        0x10745b3ee - <unknown>
   1:        0x10745a5ec - <unknown>
   2:        0x10745a66d - <unknown>
   3:        0x1074590d3 - <unknown>
   4:        0x105eb87c9 - <unknown>
   5:        0x1074c9e7e - <unknown>
   6:        0x106a30bd7 - <unknown>
   7:        0x1069ac54e - <unknown>
   8:        0x10690a7d1 - <unknown>
   9:        0x106ba7617 - <unknown>
  10:        0x1069084bd - <unknown>
  11:        0x106b43233 - <unknown>
  12:        0x10699a3d8 - <unknown>
  13:        0x106a30ce4 - <unknown>
  14:        0x1074d5fbe - <unknown>
  15:        0x106a43f72 - <unknown>
  16:        0x1074c8dd7 - <unknown>
  17:        0x1074aa908 - <unknown>
  18:     0x7fff75409660 - _pthread_body
  19:     0x7fff7540950c - _pthread_start

Thread 'IO Worker #0' panicked at 'Cannot operate with an empty validator set.', ethcore/src/engines/validator_set/simple_list.rs:96

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

2018-09-05 15:06:45  Finishing work, please wait...
```

**expedted behavior**
- no error

**Comment by dvdplm** [comment]
Can you share the contents of your `node0.toml` please?

**Comment by Hann** [comment]
this is `node0.toml` file.
```
[parity]
chain = "demo-spec.json"
base_path = "/Users/jaehyeonju/Documents/parity_eth/account_node0"
[network]
port = 30300
[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8450
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x00bd138abd70e2f00903268f3db08f2d25677c9e"
reseal_on_txs = "none"
```

but I found the problem. my mistake is `validators` param in `demo-spec.json` . I pasted `validators` like this

```
    "accounts": {
        "0x00bd138abd70e2f00903268f3db08f2d25677c9e": { "balance": "100000" },
        "0x004ec07d2329997267ec62b4166639513386f32e": { "balance": "100000" },
        "0x00aa39d30f0d20ff03a22ccfc30b7efbfca597c2": { "balance": "100000" }
    },
    "validators": {
        "list": [
            "0x7d577a597b2742b498cb5cf0c26cdcd726d39e6e",
            "0x82a978b3f5962a5b0957d9ee9eef472ee55b42f1"
        ]
    }
```
so I move `validators` to `params`.  finally it works!

**Comment by dvdplm** [comment]
Glad you figured it out! :)
