### ISSUE TITLE
Thread '<unnamed>' panicked at 'Expected to find transaction hash. Database is probably corrupted', libcore/option.rs:989

### ISSUE THREAD

**Issue by logan81k** [paritytech/parity-ethereum#9837]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.0.8
- **Operating system**: Ubuntu
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum 
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

```
Oct 31 06:13:38 node-eth-parity-2 parity[109311]: ====================
Oct 31 06:13:38 node-eth-parity-2 parity[109311]: stack backtrace:
Oct 31 06:13:38 node-eth-parity-2 parity[109311]:    0:     0x558d3c05760c - <no info>
Oct 31 06:13:38 node-eth-parity-2 parity[109311]:    1:     0x558d3c0573c2 - <no info>
Oct 31 06:13:38 node-eth-parity-2 parity[109311]:    2:     0x558d3c057438 - <no info>
...
...
...
Oct 31 06:13:38 node-eth-parity-2 parity[109311]:   33:     0x7fc48e3286b9 - <no info>
Oct 31 06:13:38 node-eth-parity-2 parity[109311]:   34:     0x7fc48de4841c - <no info>
Oct 31 06:13:38 node-eth-parity-2 parity[109311]:   35:                0x0 - <no info>
Oct 31 06:13:38 node-eth-parity-2 parity[109311]: Thread '<unnamed>' panicked at 'Expected to find transaction hash. Database is probably corrupted', libcore/option.rs:989
Oct 31 06:13:38 node-eth-parity-2 parity[109311]: This is a bug. Please report it at:
Oct 31 06:13:38 node-eth-parity-2 parity[109311]:     https://github.com/paritytech/parity/issues/new
Oct 31 06:13:38 node-eth-parity-2 parity[109311]: 2018-10-31 06:13:38 UTC Finishing work, please wait...
Oct 31 06:13:38 node-eth-parity-2 parity[109311]: 2018-10-31 06:13:38 UTC Imported #6615948 0x045a…d4f4 (142 txs, 7.99 Mgas, 926 ms, 20.40 KiB) + another 1 block(s) containing 3 tx(s)
Oct 31 06:14:39 node-eth-parity-2 parity[109311]: 2018-10-31 06:14:39 UTC Shutdown is taking longer than expected.
Oct 31 06:17:01 node-eth-parity-2 CRON[49717]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct 31 06:17:07 node-eth-parity-2 systemd[49721]: Reached target Sockets.
Oct 31 06:17:07 node-eth-parity-2 systemd[49721]: Reached target Paths.
Oct 31 06:17:07 node-eth-parity-2 systemd[49721]: Reached target Timers.
Oct 31 06:17:07 node-eth-parity-2 systemd[49721]: Reached target Basic System.
Oct 31 06:17:07 node-eth-parity-2 systemd[49721]: Reached target Default.
Oct 31 06:17:07 node-eth-parity-2 systemd[49721]: Startup finished in 11ms.
Oct 31 06:17:07 node-eth-parity-2 systemd[1]: Started User Manager for UID 1002.
Oct 31 06:18:36 node-eth-parity-2 systemd[1]: Starting Daily apt upgrade and clean activities...
Oct 31 06:18:39 node-eth-parity-2 parity[109311]: 2018-10-31 06:18:39 UTC Shutdown timeout reached, exiting uncleanly.
Oct 31 06:18:39 node-eth-parity-2 systemd[1]: parity.service: Main process exited, code=exited, status=1/FAILURE
Oct 31 06:18:39 node-eth-parity-2 systemd[1]: parity.service: Unit entered failed state.
Oct 31 06:18:39 node-eth-parity-2 systemd[1]: parity.service: Failed with result 'exit-code'.
Oct 31 06:18:39 node-eth-parity-2 systemd[1]: parity.service: Service hold-off time over, scheduling restart.
Oct 31 06:18:39 node-eth-parity-2 systemd[1]: Stopped Parity Ethereum Daemon.
Oct 31 06:18:39 node-eth-parity-2 systemd[1]: Started Parity Ethereum Daemon.
Oct 31 06:18:39 node-eth-parity-2 parity[49899]: Loading config file from /data/config.toml
Oct 31 06:18:39 node-eth-parity-2 parity[49899]: 2018-10-31 06:18:39 UTC Starting Parity-Ethereum/v2.0.8-stable-ef8f95e-20181015/x86_64-linux-gnu/rustc1.29.0
....
....
Oct 31 06:18:39 node-eth-parity-2 parity[49899]: 2018-10-31 06:18:39 UTC State DB configuration: archive +Trace
Oct 31 06:18:39 node-eth-parity-2 parity[49899]: 2018-10-31 06:18:39 UTC Operating mode: active
Oct 31 06:18:43 node-eth-parity-2 systemd[1]: Started Daily apt upgrade and clean activities.
Oct 31 06:18:44 node-eth-parity-2 parity[49899]: 2018-10-31 06:18:44 UTC Configured for Foundation using Ethash engine
Oct 31 06:18:45 node-eth-parity-2 parity[49899]: 2018-10-31 06:18:45 UTC Updated conversion rate to Ξ1 = US$195.85 (24314038 wei/gas)
```

I got this error above today. 
And I found a issue(https://github.com/paritytech/parity-ethereum/issues/8964) 
but I don't use docker. 

Anyway, Should I check RAM and Disk? How to check?

**Comment by joshua-mir** [comment]
Firstly: what kind of hardware are you running on? Database corruption almost always indicates old, damaged, or misconfigured hardware.

**Comment by logan81k** [comment]
It is running on AWS.

I create ec2 with this.
ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180814-d83d0782-cb94-46d7-8993-f4ce15d1a484-ami-04169656fea786776.4

**Comment by joshua-mir** [comment]
Well in that case you probably don't have control over the hardware, :sweat_smile: how much space is available to parity and are you still receiving this error after restarting? 

You can only really use `parity db kill` and resync if the error is recurring on restart. If you don't have enough storage space available to your instance, you will see this error every time your disk is full. If you don't see this error anymore after restarting... I wouldn't worry about it.

**Comment by logan81k** [comment]
I think I have enough disk. 
The below is a result of "df -h" command

/dev/xvdb                                       8.0T  1.7T  5.9T  23% /data

And I don't get this error yet after restarting.

**Comment by joshua-mir** [comment]
Yep that's more than enough space... let me know if this happens again. Closing for now.

**Comment by logan81k** [comment]
Ok. Thanks for you support.
Have a good day.
