### ISSUE TITLE
parity 2.0.8 fails with --fat-db=on

### ISSUE THREAD

**Issue by allenday** [paritytech/parity-ethereum#9892]
- **Parity Ethereum version**: 2.0.8
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

```
docker run -v /data:/data -p 3389:8545 -ti parity/parity:v2.0.8 --jsonrpc-interface=all --jsonrpc-port=8545 --jsonrpc-apis=all --tracing=on --pruning=archive --db-compaction=ssd -d /data -l info --fat-db=on
2018-11-12 01:41:05 UTC Starting Parity-Ethereum/v2.0.8-stable-ef8f95e-20181015/x86_64-linux-gnu/rustc1.29.0
2018-11-12 01:41:05 UTC Keys path /data/keys/ethereum
2018-11-12 01:41:05 UTC DB path /data/chains/ethereum/db/906a34e69aec8c0d
2018-11-12 01:41:05 UTC State DB configuration: archive +Fat +Trace
2018-11-12 01:41:05 UTC Operating mode: active
2018-11-12 01:41:05 UTC Warning: Warp Sync is disabled because Fat DB is turned on.
2018-11-12 01:41:06 UTC Configured for Foundation using Ethash engine
2018-11-12 01:41:08 UTC Updated conversion rate to Ξ1 = US$212.61 (22397370 wei/gas)

====================

stack backtrace:
   0:     0x55c0c36f760c - <no info>
   1:     0x55c0c36f73c2 - <no info>
   2:     0x55c0c36f7438 - <no info>
   3:     0x55c0c36f623a - <no info>
   4:     0x55c0c219e085 - <no info>
   5:     0x55c0c3757233 - <no info>
   6:     0x55c0c371f076 - <no info>
   7:     0x55c0c371e474 - <no info>
   8:     0x55c0c2e030a5 - <no info>
   9:     0x55c0c2dbfe65 - <no info>
  10:     0x55c0c2ae6e19 - <no info>
  11:     0x55c0c2e84902 - <no info>
  12:     0x55c0c2de6385 - <no info>
  13:     0x55c0c2de7717 - <no info>
  14:     0x55c0c2ded43a - <no info>
  15:     0x55c0c2e4b62d - <no info>
  16:     0x55c0c37814a9 - <no info>
  17:     0x55c0c2f1b8d9 - <no info>
  18:     0x55c0c3759cba - <no info>
  19:     0x55c0c3757805 - <no info>
  20:     0x7ff60a4296b9 - <no info>
  21:     0x7ff609f4941c - <no info>
  22:                0x0 - <no info>

Thread 'Verifier #0' panicked at 'assertion failed: rc == -1', util/journaldb/src/archivedb.rs:141

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

2018-11-12 01:41:14 UTC Finishing work, please wait...
2018-11-12 01:41:14 UTC Block import failed for #1590283 (0x9505…ee7c): Parent not found (0xcb85…b1d0) 

====================

stack backtrace:
   0:     0x55c0c36f760c - <no info>
   1:     0x55c0c36f73c2 - <no info>
   2:     0x55c0c36f7438 - <no info>
   3:     0x55c0c36f623a - <no info>
   4:     0x55c0c219e085 - <no info>
   5:     0x55c0c3757233 - <no info>
   6:     0x55c0c3756dd9 - <no info>
   7:     0x55c0c3756cd5 - <no info>
   8:     0x55c0c37b8c9b - <no info>
   9:     0x55c0c22e2d5f - <no info>
  10:     0x55c0c2237f3f - <no info>
  11:     0x55c0c2332500 - <no info>
  12:     0x55c0c2330de3 - <no info>
  13:     0x55c0c231e1ef - <no info>
  14:     0x55c0c232051d - <no info>
  15:     0x55c0c231c030 - <no info>
  16:     0x55c0c23cf865 - <no info>
  17:     0x55c0c2324381 - <no info>
  18:     0x55c0c21ea83b - <no info>
  19:     0x55c0c343009a - <no info>
  20:     0x55c0c342ef00 - <no info>
  21:     0x55c0c342cf28 - <no info>
  22:     0x55c0c342809b - <no info>
  23:     0x55c0c37814a9 - <no info>
  24:     0x55c0c342f63a - <no info>
  25:     0x55c0c3759cba - <no info>
  26:     0x55c0c3757805 - <no info>
  27:     0x7ff60a4296b9 - <no info>
  28:     0x7ff609f4941c - <no info>
  29:                0x0 - <no info>
Thread '<unnamed>' panicked at 'Propagating verifier thread panic on shutdown: Any', libcore/result.rs:945
This is a bug. Please report it at:
    https://github.com/paritytech/parity/issues/new
```

**Comment by allenday** [comment]
A second node failed with the same config and same command and a similar stack trace:
```

stack backtrace:
   0:     0x56375381360c - <no info>
   1:     0x5637538133c2 - <no info>
   2:     0x563753813438 - <no info>
   3:     0x56375381223a - <no info>
   4:     0x5637522ba085 - <no info>
   5:     0x563753873233 - <no info>
   6:     0x56375383b076 - <no info>
   7:     0x56375383a474 - <no info>
   8:     0x563752f1f0a5 - <no info>
   9:     0x563752edbe65 - <no info>
  10:     0x563752c02e19 - <no info>
  11:     0x563752c20bb1 - <no info>
  12:     0x563752c03a90 - <no info>
  13:     0x563752c0a236 - <no info>
  14:     0x56375389d4a9 - <no info>
  15:     0x563752c1b752 - <no info>
  16:     0x563753875cba - <no info>
  17:     0x563753873805 - <no info>
  18:     0x7f6ba1ab26b9 - <no info>
  19:     0x7f6ba15d241c - <no info>
  20:                0x0 - <no info>

Thread 'IO Worker #3' panicked at 'assertion failed: rc == -1', util/journaldb/src/archivedb.rs:141

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

2018-11-09 23:01:25 UTC Finishing work, please wait...
2018-11-09 23:01:25 UTC Block import failed for #1590284 (0xa0d1…54d6): Parent not found (0x9505…ee7c)
```

**Comment by joshua-mir** [comment]
I'm implying from the compaction=ssd line that you are running on an ssd, but can you share more about your system? ie, what filesystem are you using and if your /data dir is in a volume, how is it mounted?

**Comment by allenday** [comment]
Yes is is an ext4 SSD volume, 10TB GCP persistent disk. It's not mounted
with any special options.

**Comment by joshua-mir** [comment]
Hey, this looks like the same issue as https://github.com/paritytech/parity-ethereum/issues/9180 actually. Fix is in the beta release in case this is important.
