### ISSUE TITLE
before i sync the all data with my peer, can i use web3 to connect the rpc port ?

### ISSUE THREAD

**Issue by w1397800** [paritytech/parity-ethereum#9951]
my node is sync the data on mainchain, but the connection is refused when i use web3 to connect the rpc port. Here is my config.toml .
`[rpc]
port = 39842  
disable = false
apis = ["all"]  
cors = ["*"]
hosts = ["all"]`

look forward to your reply.

**Comment by joshua-mir** [comment]
Hey, can you share any information about your platform, version of parity, or log output from around this time? You shouldn't be getting refused connections with that config. 

Also, I'd check that you've configured your web3 library of choice to use your custom rpc port instead of the default 8545

**Comment by joshua-mir** [comment]
Hey, perhaps this is related to you trying to connect to parity at `192.168.1.9` which I presume is your ip address on your LAN, while parity is listening on localhost. Can you try connecting to `0.0.0.0`, or `127.0.0.1`?

**Comment by w1397800** [comment]
yeah, it works by  changing to interface = "0.0.0.0" in node1.toml.
but here is another issue.

public void testTrace() throws Exception {
	Parity web3j = Parity.build(new HttpService("http://192.168.1.9:8545"));
	Web3ClientVersion web3ClientVersion = web3j.web3ClientVersion().send();
	System.out.println(web3ClientVersion.getWeb3ClientVersion());
    }

Exception in thread "main" org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: okhttp3.internal.http.RealResponseBody@1445d7f
	at org.web3j.protocol.http.HttpService.performIO(HttpService.java:114)
	at org.web3j.protocol.Service.send(Service.java:31)
	at org.web3j.protocol.core.Request.send(Request.java:71)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.getBlockNumber(JsonRpc2_0Rx.java:227)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.getLatestBlockNumber(JsonRpc2_0Rx.java:218)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.catchUpToLatestBlockObservableSync(JsonRpc2_0Rx.java:174)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.catchUpToLatestBlockObservable(JsonRpc2_0Rx.java:155)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.catchUpToLatestAndSubscribeToNewBlocksObservable(JsonRpc2_0Rx.java:205)
	at org.web3j.protocol.core.JsonRpc2_0Web3j.catchUpToLatestAndSubscribeToNewBlocksObservable(JsonRpc2_0Web3j.java:767)
	at com.ethjava.Filter.catchUpFilter(Filter.java:121)
	at com.ethjava.Filter.main(Filter.java:56)

**Comment by joshua-mir** [comment]
I meant change the ip that web3j is connecting to, but if that works for you... 😅

I can't figure out how that error is related to the example code you're using, do you have a similar error on other rpc requests?

This doesn't seem like a parity related issue.
